// Code generated by tools/contracts/generate.mjs; DO NOT EDIT.
package core

type DownloadJob struct {
	ID              string         `json:"id"`
	DedupKey        string         `json:"dedupKey"`
	Status          DownloadStatus `json:"status"`
	Progress        int            `json:"progress"`
	Error           string         `json:"error,omitempty"`
	OutputPath      string         `json:"outputPath,omitempty"`
	LibraryTrackID  string         `json:"libraryTrackId,omitempty"`
	CoverArtID      string         `json:"coverArtId,omitempty"`
	CanonicalID     string         `json:"canonicalId,omitempty"`
	DownloaderName  string         `json:"downloaderName"`
	Priority        int            `json:"priority"`
	Attempts        int            `json:"attempts"`
	Source          string         `json:"source"`
	ExternalID      string         `json:"externalId"`
	Artist          string         `json:"artist,omitempty"`
	Title           string         `json:"title,omitempty"`
	Album           string         `json:"album,omitempty"`
	ISRC            string         `json:"isrc,omitempty"`
	DurationMs      int            `json:"durationMs,omitempty"`
	PlayWhenReady   bool           `json:"playWhenReady"`
	AddToPlaylistID string         `json:"addToPlaylistId,omitempty"`
	Quality         AudioQuality   `json:"quality,omitempty"`
	DownloaderRef   string         `json:"downloaderRef,omitempty"`
	CreatedAt       int64          `json:"createdAt"`
	StartedAt       int64          `json:"startedAt"`
	FinishedAt      int64          `json:"finishedAt"`
}

type DownloadEvent struct {
	JobID          string         `json:"jobId"`
	DedupKey       string         `json:"dedupKey"`
	Status         DownloadStatus `json:"status"`
	Progress       int            `json:"progress"`
	Error          string         `json:"error,omitempty"`
	Source         string         `json:"source"`
	ExternalID     string         `json:"externalId"`
	LibraryTrackID string         `json:"libraryTrackId,omitempty"`
	CoverArtID     string         `json:"coverArtId,omitempty"`
	CanonicalID    string         `json:"canonicalId,omitempty"`
	ArtistID       string         `json:"artistId,omitempty"`
	AlbumID        string         `json:"albumId,omitempty"`
}

type LibraryUpdatedEvent struct {
	ArtistIDs []string `json:"artistIds"`
	AlbumIDs  []string `json:"albumIds"`
}

type DownloadRemovedEvent struct {
	JobIDs []string `json:"jobIds"`
}

type QueueStateEvent struct {
	Paused bool `json:"paused"`
}

type CreateDownloadRequest struct {
	Source          string `json:"source"`
	ExternalID      string `json:"externalId"`
	Artist          string `json:"artist"`
	Title           string `json:"title"`
	Album           string `json:"album"`
	ISRC            string `json:"isrc"`
	DurationMs      int    `json:"durationMs"`
	PlayWhenReady   bool   `json:"playWhenReady"`
	AddToPlaylistID string `json:"addToPlaylistId,omitempty"`
	Quality         string `json:"quality,omitempty"`
}
