import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import YAML from 'yaml'
import Ajv from 'ajv'
import standaloneCode from 'ajv/dist/standalone/index.js'

process.chdir(fileURLToPath(new URL('../..', import.meta.url)))
const check = process.argv.includes('--check')
function emit(path, content) {
  if (check) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`Generated file is stale: ${path}`)
  } else writeFileSync(path, content)
}
const document = YAML.parse(readFileSync('internal/api/openapi.yaml', 'utf8'))
const schemas = document.components.schemas
execFileSync('tools/contracts/node_modules/.bin/openapi-typescript', ['internal/api/openapi.yaml', '-o', 'web/src/lib/generated/api.d.ts', ...(check ? ['--check'] : [])], { stdio: 'inherit' })

// Only explicitly marked flat transport records are emitted into Go. Domain
// behavior stays handwritten. Fail on unsupported shapes instead of guessing.
let go = '// Code generated by tools/contracts/generate.mjs; DO NOT EDIT.\npackage core\n\n'
for (const [name, schema] of Object.entries(schemas)) {
  if (!schema['x-go-generate']) continue
  go += `type ${name} struct {\n`
  for (const [key, prop] of Object.entries(schema.properties)) {
    if (prop['x-go-ignore'] === true) {
      if (prop['x-go-name'] || prop['x-go-type']) throw new Error(`Ignored Go field has annotations: ${name}.${key}`)
      continue
    }
    if (!prop['x-go-name']) throw new Error(`Missing Go name: ${name}.${key}`)
    if (!prop['x-go-type']) throw new Error(`Missing Go type: ${name}.${key}`)
    const wireTypes = { string: 'string', DownloadStatus: 'string', AudioQuality: 'string', int: 'integer', int64: 'integer', bool: 'boolean', '[]string': 'array' }
    const wireType = wireTypes[prop['x-go-type']]
    if (!wireType || prop.type !== wireType || (wireType === 'array' && prop.items?.type !== 'string') || (prop.nullable && wireType !== 'array')) {
      throw new Error(`Incompatible Go type: ${name}.${key}`)
    }
    const omit = prop['x-go-omitempty'] ?? !schema.required?.includes(key)
    go += `${prop['x-go-name']} ${prop['x-go-type']} \`json:"${key}${omit ? ',omitempty' : ''}"\`\n`
  }
  go += '}\n\n'
}
emit('internal/core/download_wire.gen.go', execFileSync('gofmt', { input: go, encoding: 'utf8' }))

const ajv = new Ajv({ strict: false, validateFormats: false, code: { source: true, esm: true } })
ajv.addSchema({ $id: 'reverb', components: { schemas } })
emit('web/src/lib/generated/validateRealtime.js', '// Generated; DO NOT EDIT.\n' + standaloneCode(ajv, { validateRealtime: 'reverb#/components/schemas/RealtimeEvent' }))
emit('web/src/lib/generated/validateRealtime.d.ts', `// Generated; DO NOT EDIT.\nimport type { components } from './api'\nexport function validateRealtime(value: unknown): value is components['schemas']['RealtimeEvent']\n`)
