import { readFileSync, writeFileSync } from 'node:fs'
import { execFileSync } from 'node:child_process'
import { fileURLToPath } from 'node:url'
import YAML from 'yaml'
import Ajv from 'ajv'
import standaloneCode from 'ajv/dist/standalone/index.js'

process.chdir(fileURLToPath(new URL('../..', import.meta.url)))
const check = process.argv.includes('--check')
function emit(path, content) {
  if (check) {
    if (readFileSync(path, 'utf8') !== content) throw new Error(`Generated file is stale: ${path}`)
  } else writeFileSync(path, content)
}
const document = YAML.parse(readFileSync('internal/api/openapi.yaml', 'utf8'))
// An unquoted comma in a flow-style description splits it into stray null
// keys, which strict OpenAPI parsers such as swift-openapi-generator's refuse.
;(function refuseNulls(node, path) {
  if (node === null) throw new Error(`Null value at ${path}: quote the description it was split from`)
  if (typeof node === 'object') for (const [k, v] of Object.entries(node)) refuseNulls(v, `${path}/${k}`)
})(document, '')
const schemas = document.components.schemas
execFileSync('tools/contracts/node_modules/.bin/openapi-typescript', ['internal/api/openapi.yaml', '-o', 'web/src/lib/generated/api.d.ts', ...(check ? ['--check'] : [])], { stdio: 'inherit' })

// Only explicitly marked flat transport records are emitted into Go. Domain
// behavior stays handwritten. Fail on unsupported shapes instead of guessing.
let go = '// Code generated by tools/contracts/generate.mjs; DO NOT EDIT.\npackage core\n\n'
for (const [name, schema] of Object.entries(schemas)) {
  if (!schema['x-go-generate']) continue
  go += `type ${name} struct {\n`
  for (const [key, prop] of Object.entries(schema.properties)) {
    if (prop['x-go-ignore'] === true) {
      if (prop['x-go-name'] || prop['x-go-type']) throw new Error(`Ignored Go field has annotations: ${name}.${key}`)
      continue
    }
    if (!prop['x-go-name']) throw new Error(`Missing Go name: ${name}.${key}`)
    if (!prop['x-go-type']) throw new Error(`Missing Go type: ${name}.${key}`)
    const wireTypes = { string: 'string', DownloadStatus: 'string', AudioQuality: 'string', int: 'integer', int64: 'integer', bool: 'boolean', '[]string': 'array' }
    const wireType = wireTypes[prop['x-go-type']]
    if (!wireType || prop.type !== wireType || (wireType === 'array' && prop.items?.type !== 'string') || (prop.nullable && wireType !== 'array')) {
      throw new Error(`Incompatible Go type: ${name}.${key}`)
    }
    const omit = prop['x-go-omitempty'] ?? !schema.required?.includes(key)
    go += `${prop['x-go-name']} ${prop['x-go-type']} \`json:"${key}${omit ? ',omitempty' : ''}"\`\n`
  }
  go += '}\n\n'
}
emit('internal/core/download_wire.gen.go', execFileSync('gofmt', { input: go, encoding: 'utf8' }))

const ajv = new Ajv({ strict: false, validateFormats: false, code: { source: true, esm: true } })
ajv.addSchema({ $id: 'reverb', components: { schemas } })
emit('web/src/lib/generated/validateRealtime.js', '// Generated; DO NOT EDIT.\n' + standaloneCode(ajv, { validateRealtime: 'reverb#/components/schemas/RealtimeEvent' }))
emit('web/src/lib/generated/validateRealtime.d.ts', `// Generated; DO NOT EDIT.\nimport type { components } from './api'\nexport function validateRealtime(value: unknown): value is components['schemas']['RealtimeEvent']\n`)

// The iOS app's Swift client is generated at build time by
// swift-openapi-generator from this subset: the operations the app calls, each
// named, with every component they reference. It is regenerated here and
// checked like the files above, so a change to one of those operations fails
// `make contracts-check` until the app's copy is refreshed.
const iosOperations = {
  '/health': { get: 'getHealth' },
  '/p2p/pair/redeem': { post: 'redeemPairingCode' },
  '/p2p/pair/redeem-qr': { post: 'redeemPairingQR' },
  '/pairing/devices': { get: 'listPairedDevices' },
  '/pairing/devices/{id}': { delete: 'unpairDevice' },
  '/sync/status': { get: 'getSyncStatus' },
  '/sync/trigger': { post: 'triggerSync' },
  '/library/search': { get: 'searchLibrary' },
  '/library/artists': { get: 'listLibraryArtists' },
  '/library/artist/{id}': { get: 'getLibraryArtist' },
  '/library/albums': { get: 'listLibraryAlbums' },
  '/library/album/{id}': { get: 'getLibraryAlbum' },
  '/library/songs': { get: 'listLibraryTracks' },
  '/library/catalog/tracks': { get: 'listCatalogTracks' },
  // Search is SSE, so Swift consumes its bytes directly; keep its contract in
  // the subset so drift in path, parameters, or envelopes is still checked.
  '/search/everywhere': { get: 'searchEverywhere' },
  '/playlists': { get: 'listPlaylists', post: 'createPlaylist' },
  '/playlists/{id}': { get: 'getPlaylist', put: 'renamePlaylist', delete: 'deletePlaylist' },
  '/playlists/{id}/tracks': { post: 'addPlaylistTrack', delete: 'removePlaylistTrack' },
  '/playlists/{id}/tracks/order': { put: 'reorderPlaylistTracks' },
  '/offline-set': { get: 'listOfflineSet' },
  '/offline-set/status': { get: 'getOfflineStatus' },
  '/offline-set/{playlistId}': { put: 'setPlaylistOffline', delete: 'removePlaylistOffline' },
  '/pending-uploads': { get: 'listPendingUploads' },
  '/downloads': { post: 'enqueueDownload' },
  '/links/resolve': { post: 'resolveLink' },
  '/links/add': { post: 'addFromLink' },
  '/player/{session}': { get: 'getQueue' },
  '/player/{session}/play': { post: 'playTracks' },
  '/player/{session}/jump': { post: 'jumpInQueue' },
  '/player/{session}/next': { post: 'nextInQueue' },
  '/player/{session}/previous': { post: 'previousInQueue' },
  '/player/{session}/ended': { post: 'endedInQueue' },
  '/plays': { post: 'recordPlay' },
  '/recommendations/shelves': { get: 'getHomeShelves' },
  '/recommendations/mixes': { get: 'listMixes' },
  '/recommendations/mixes/{kind}': { get: 'getMix' },
  '/recommendations/mixes/{kind}/playlist': { post: 'saveMixAsPlaylist' },
  '/not-interested': { post: 'markNotInterested' },
}
const ios = { openapi: document.openapi, info: { ...document.info, title: 'Reverb API (iOS subset)' }, servers: document.servers, paths: {}, components: {} }
const wanted = new Set()
function collectRefs(node) {
  if (Array.isArray(node)) return node.forEach(collectRefs)
  if (!node || typeof node !== 'object') return
  for (const [key, value] of Object.entries(node)) {
    if (key === '$ref' && typeof value === 'string') {
      const ref = value.replace('#/components/', '')
      if (!wanted.has(ref)) {
        wanted.add(ref)
        const [kind, name] = ref.split('/')
        const target = document.components[kind]?.[name]
        if (!target) throw new Error(`Unresolved reference: ${value}`)
        collectRefs(target)
      }
    } else collectRefs(value)
  }
}
for (const [path, methods] of Object.entries(iosOperations)) {
  if (!document.paths[path]) throw new Error(`iOS operation path is gone: ${path}`)
  ios.paths[path] = {}
  for (const [method, operationId] of Object.entries(methods)) {
    const op = document.paths[path][method]
    if (!op) throw new Error(`iOS operation is gone: ${method.toUpperCase()} ${path}`)
    ios.paths[path][method] = { operationId, ...op }
    collectRefs(op)
  }
}
for (const ref of [...wanted].sort()) {
  const [kind, name] = ref.split('/')
  ;(ios.components[kind] ??= {})[name] = document.components[kind][name]
}
emit('ios/ReverbKit/Sources/ReverbAPI/openapi.yaml', '# Generated by tools/contracts/generate.mjs from internal/api/openapi.yaml; DO NOT EDIT.\n' + YAML.stringify(ios, { lineWidth: 0 }))
