// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: catalog.sql

package db

import (
	"context"
)

const deleteBindingsForCatalog = `-- name: DeleteBindingsForCatalog :exec
DELETE FROM backend_binding WHERE catalog_id = ?
`

func (q *Queries) DeleteBindingsForCatalog(ctx context.Context, catalogID string) error {
	_, err := q.db.ExecContext(ctx, deleteBindingsForCatalog, catalogID)
	return err
}

const deleteCatalogEntity = `-- name: DeleteCatalogEntity :exec
DELETE FROM catalog_entity WHERE id = ?
`

func (q *Queries) DeleteCatalogEntity(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteCatalogEntity, id)
	return err
}

const getAliasCatalogID = `-- name: GetAliasCatalogID :one
SELECT catalog_id FROM catalog_alias WHERE alias_kind = ? AND alias_value = ?
`

type GetAliasCatalogIDParams struct {
	AliasKind  string `json:"alias_kind"`
	AliasValue string `json:"alias_value"`
}

func (q *Queries) GetAliasCatalogID(ctx context.Context, arg GetAliasCatalogIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getAliasCatalogID, arg.AliasKind, arg.AliasValue)
	var catalog_id string
	err := row.Scan(&catalog_id)
	return catalog_id, err
}

const getBackendBinding = `-- name: GetBackendBinding :one
SELECT catalog_id, library_identity, backend_id, cover_art_id, known_absent, binding_epoch, resolved_at FROM backend_binding WHERE catalog_id = ? AND library_identity = ?
`

type GetBackendBindingParams struct {
	CatalogID       string `json:"catalog_id"`
	LibraryIdentity string `json:"library_identity"`
}

func (q *Queries) GetBackendBinding(ctx context.Context, arg GetBackendBindingParams) (BackendBinding, error) {
	row := q.db.QueryRowContext(ctx, getBackendBinding, arg.CatalogID, arg.LibraryIdentity)
	var i BackendBinding
	err := row.Scan(
		&i.CatalogID,
		&i.LibraryIdentity,
		&i.BackendID,
		&i.CoverArtID,
		&i.KnownAbsent,
		&i.BindingEpoch,
		&i.ResolvedAt,
	)
	return i, err
}

const getCatalogEntity = `-- name: GetCatalogEntity :one
SELECT id, kind, title, artist, album, duration_ms, isrc, mbid, source, external_id, created_at FROM catalog_entity WHERE id = ?
`

func (q *Queries) GetCatalogEntity(ctx context.Context, id string) (CatalogEntity, error) {
	row := q.db.QueryRowContext(ctx, getCatalogEntity, id)
	var i CatalogEntity
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Title,
		&i.Artist,
		&i.Album,
		&i.DurationMs,
		&i.Isrc,
		&i.Mbid,
		&i.Source,
		&i.ExternalID,
		&i.CreatedAt,
	)
	return i, err
}

const insertCatalogAlias = `-- name: InsertCatalogAlias :exec
INSERT INTO catalog_alias (alias_kind, alias_value, catalog_id, created_at)
VALUES (?,?,?,?) ON CONFLICT(alias_kind, alias_value) DO NOTHING
`

type InsertCatalogAliasParams struct {
	AliasKind  string `json:"alias_kind"`
	AliasValue string `json:"alias_value"`
	CatalogID  string `json:"catalog_id"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) InsertCatalogAlias(ctx context.Context, arg InsertCatalogAliasParams) error {
	_, err := q.db.ExecContext(ctx, insertCatalogAlias,
		arg.AliasKind,
		arg.AliasValue,
		arg.CatalogID,
		arg.CreatedAt,
	)
	return err
}

const insertCatalogEntity = `-- name: InsertCatalogEntity :exec
INSERT INTO catalog_entity (id, kind, title, artist, album, duration_ms, isrc, mbid, source, external_id, created_at)
VALUES (?,?,?,?,?,?,?,?,?,?,?)
`

type InsertCatalogEntityParams struct {
	ID         string `json:"id"`
	Kind       string `json:"kind"`
	Title      string `json:"title"`
	Artist     string `json:"artist"`
	Album      string `json:"album"`
	DurationMs int64  `json:"duration_ms"`
	Isrc       string `json:"isrc"`
	Mbid       string `json:"mbid"`
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) InsertCatalogEntity(ctx context.Context, arg InsertCatalogEntityParams) error {
	_, err := q.db.ExecContext(ctx, insertCatalogEntity,
		arg.ID,
		arg.Kind,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.DurationMs,
		arg.Isrc,
		arg.Mbid,
		arg.Source,
		arg.ExternalID,
		arg.CreatedAt,
	)
	return err
}

const listAliasesForCatalog = `-- name: ListAliasesForCatalog :many
SELECT alias_kind, alias_value FROM catalog_alias WHERE catalog_id = ?
`

type ListAliasesForCatalogRow struct {
	AliasKind  string `json:"alias_kind"`
	AliasValue string `json:"alias_value"`
}

func (q *Queries) ListAliasesForCatalog(ctx context.Context, catalogID string) ([]ListAliasesForCatalogRow, error) {
	rows, err := q.db.QueryContext(ctx, listAliasesForCatalog, catalogID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAliasesForCatalogRow
	for rows.Next() {
		var i ListAliasesForCatalogRow
		if err := rows.Scan(&i.AliasKind, &i.AliasValue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointAliases = `-- name: RepointAliases :exec
UPDATE catalog_alias SET catalog_id = ? WHERE catalog_id = ?
`

type RepointAliasesParams struct {
	CatalogID   string `json:"catalog_id"`
	CatalogID_2 string `json:"catalog_id_2"`
}

func (q *Queries) RepointAliases(ctx context.Context, arg RepointAliasesParams) error {
	_, err := q.db.ExecContext(ctx, repointAliases, arg.CatalogID, arg.CatalogID_2)
	return err
}

const repointBindings = `-- name: RepointBindings :exec
UPDATE backend_binding SET catalog_id = ? WHERE catalog_id = ?
`

type RepointBindingsParams struct {
	CatalogID   string `json:"catalog_id"`
	CatalogID_2 string `json:"catalog_id_2"`
}

func (q *Queries) RepointBindings(ctx context.Context, arg RepointBindingsParams) error {
	_, err := q.db.ExecContext(ctx, repointBindings, arg.CatalogID, arg.CatalogID_2)
	return err
}

const upsertBackendBinding = `-- name: UpsertBackendBinding :exec
INSERT INTO backend_binding (catalog_id, library_identity, backend_id, cover_art_id, known_absent, binding_epoch, resolved_at)
VALUES (?,?,?,?,?,?,?)
ON CONFLICT(catalog_id, library_identity) DO UPDATE SET
  backend_id=excluded.backend_id, cover_art_id=excluded.cover_art_id,
  known_absent=excluded.known_absent, binding_epoch=excluded.binding_epoch, resolved_at=excluded.resolved_at
`

type UpsertBackendBindingParams struct {
	CatalogID       string `json:"catalog_id"`
	LibraryIdentity string `json:"library_identity"`
	BackendID       string `json:"backend_id"`
	CoverArtID      string `json:"cover_art_id"`
	KnownAbsent     int64  `json:"known_absent"`
	BindingEpoch    int64  `json:"binding_epoch"`
	ResolvedAt      int64  `json:"resolved_at"`
}

func (q *Queries) UpsertBackendBinding(ctx context.Context, arg UpsertBackendBindingParams) error {
	_, err := q.db.ExecContext(ctx, upsertBackendBinding,
		arg.CatalogID,
		arg.LibraryIdentity,
		arg.BackendID,
		arg.CoverArtID,
		arg.KnownAbsent,
		arg.BindingEpoch,
		arg.ResolvedAt,
	)
	return err
}
