// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: coverage.sql

package db

import (
	"context"
)

const getAlbumCoverage = `-- name: GetAlbumCoverage :one
SELECT source, external_album_id, coverage_json, library_album_id, fetched_at, library_version FROM album_coverage WHERE source = ? AND external_album_id = ?
`

type GetAlbumCoverageParams struct {
	Source          string `json:"source"`
	ExternalAlbumID string `json:"external_album_id"`
}

func (q *Queries) GetAlbumCoverage(ctx context.Context, arg GetAlbumCoverageParams) (AlbumCoverage, error) {
	row := q.db.QueryRowContext(ctx, getAlbumCoverage, arg.Source, arg.ExternalAlbumID)
	var i AlbumCoverage
	err := row.Scan(
		&i.Source,
		&i.ExternalAlbumID,
		&i.CoverageJson,
		&i.LibraryAlbumID,
		&i.FetchedAt,
		&i.LibraryVersion,
	)
	return i, err
}

const getAlbumExternalMap = `-- name: GetAlbumExternalMap :one
SELECT library_album_id, source, external_album_id, confidence, created_at FROM album_external_map WHERE library_album_id = ? AND source = ?
`

type GetAlbumExternalMapParams struct {
	LibraryAlbumID string `json:"library_album_id"`
	Source         string `json:"source"`
}

func (q *Queries) GetAlbumExternalMap(ctx context.Context, arg GetAlbumExternalMapParams) (AlbumExternalMap, error) {
	row := q.db.QueryRowContext(ctx, getAlbumExternalMap, arg.LibraryAlbumID, arg.Source)
	var i AlbumExternalMap
	err := row.Scan(
		&i.LibraryAlbumID,
		&i.Source,
		&i.ExternalAlbumID,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const getArtistExternalMap = `-- name: GetArtistExternalMap :one
SELECT library_artist_id, source, external_artist_id, confidence, created_at FROM artist_external_map WHERE library_artist_id = ? AND source = ?
`

type GetArtistExternalMapParams struct {
	LibraryArtistID string `json:"library_artist_id"`
	Source          string `json:"source"`
}

func (q *Queries) GetArtistExternalMap(ctx context.Context, arg GetArtistExternalMapParams) (ArtistExternalMap, error) {
	row := q.db.QueryRowContext(ctx, getArtistExternalMap, arg.LibraryArtistID, arg.Source)
	var i ArtistExternalMap
	err := row.Scan(
		&i.LibraryArtistID,
		&i.Source,
		&i.ExternalArtistID,
		&i.Confidence,
		&i.CreatedAt,
	)
	return i, err
}

const getDiscographyCache = `-- name: GetDiscographyCache :one
SELECT source, external_artist_id, albums_json, fetched_at FROM discography_cache WHERE source = ? AND external_artist_id = ?
`

type GetDiscographyCacheParams struct {
	Source           string `json:"source"`
	ExternalArtistID string `json:"external_artist_id"`
}

func (q *Queries) GetDiscographyCache(ctx context.Context, arg GetDiscographyCacheParams) (DiscographyCache, error) {
	row := q.db.QueryRowContext(ctx, getDiscographyCache, arg.Source, arg.ExternalArtistID)
	var i DiscographyCache
	err := row.Scan(
		&i.Source,
		&i.ExternalArtistID,
		&i.AlbumsJson,
		&i.FetchedAt,
	)
	return i, err
}

const listCachedDiscographies = `-- name: ListCachedDiscographies :many
SELECT m.library_artist_id, m.source, m.external_artist_id, d.albums_json
FROM artist_external_map m
JOIN discography_cache d ON d.source = m.source AND d.external_artist_id = m.external_artist_id
`

type ListCachedDiscographiesRow struct {
	LibraryArtistID  string `json:"library_artist_id"`
	Source           string `json:"source"`
	ExternalArtistID string `json:"external_artist_id"`
	AlbumsJson       string `json:"albums_json"`
}

func (q *Queries) ListCachedDiscographies(ctx context.Context) ([]ListCachedDiscographiesRow, error) {
	rows, err := q.db.QueryContext(ctx, listCachedDiscographies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCachedDiscographiesRow
	for rows.Next() {
		var i ListCachedDiscographiesRow
		if err := rows.Scan(
			&i.LibraryArtistID,
			&i.Source,
			&i.ExternalArtistID,
			&i.AlbumsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAlbumCoverage = `-- name: UpsertAlbumCoverage :exec
INSERT INTO album_coverage (source, external_album_id, coverage_json, library_album_id, library_version, fetched_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(source, external_album_id) DO UPDATE SET
  coverage_json = excluded.coverage_json, library_album_id = excluded.library_album_id,
  library_version = excluded.library_version, fetched_at = excluded.fetched_at
`

type UpsertAlbumCoverageParams struct {
	Source          string `json:"source"`
	ExternalAlbumID string `json:"external_album_id"`
	CoverageJson    string `json:"coverage_json"`
	LibraryAlbumID  string `json:"library_album_id"`
	LibraryVersion  int64  `json:"library_version"`
	FetchedAt       int64  `json:"fetched_at"`
}

func (q *Queries) UpsertAlbumCoverage(ctx context.Context, arg UpsertAlbumCoverageParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlbumCoverage,
		arg.Source,
		arg.ExternalAlbumID,
		arg.CoverageJson,
		arg.LibraryAlbumID,
		arg.LibraryVersion,
		arg.FetchedAt,
	)
	return err
}

const upsertAlbumExternalMap = `-- name: UpsertAlbumExternalMap :exec
INSERT INTO album_external_map (library_album_id, source, external_album_id, confidence, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(library_album_id, source) DO UPDATE SET
  external_album_id = excluded.external_album_id, confidence = excluded.confidence
`

type UpsertAlbumExternalMapParams struct {
	LibraryAlbumID  string  `json:"library_album_id"`
	Source          string  `json:"source"`
	ExternalAlbumID string  `json:"external_album_id"`
	Confidence      float64 `json:"confidence"`
	CreatedAt       int64   `json:"created_at"`
}

func (q *Queries) UpsertAlbumExternalMap(ctx context.Context, arg UpsertAlbumExternalMapParams) error {
	_, err := q.db.ExecContext(ctx, upsertAlbumExternalMap,
		arg.LibraryAlbumID,
		arg.Source,
		arg.ExternalAlbumID,
		arg.Confidence,
		arg.CreatedAt,
	)
	return err
}

const upsertArtistExternalMap = `-- name: UpsertArtistExternalMap :exec
INSERT INTO artist_external_map (library_artist_id, source, external_artist_id, confidence, created_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(library_artist_id, source) DO UPDATE SET
  external_artist_id = excluded.external_artist_id, confidence = excluded.confidence
`

type UpsertArtistExternalMapParams struct {
	LibraryArtistID  string  `json:"library_artist_id"`
	Source           string  `json:"source"`
	ExternalArtistID string  `json:"external_artist_id"`
	Confidence       float64 `json:"confidence"`
	CreatedAt        int64   `json:"created_at"`
}

func (q *Queries) UpsertArtistExternalMap(ctx context.Context, arg UpsertArtistExternalMapParams) error {
	_, err := q.db.ExecContext(ctx, upsertArtistExternalMap,
		arg.LibraryArtistID,
		arg.Source,
		arg.ExternalArtistID,
		arg.Confidence,
		arg.CreatedAt,
	)
	return err
}

const upsertDiscographyCache = `-- name: UpsertDiscographyCache :exec
INSERT INTO discography_cache (source, external_artist_id, albums_json, fetched_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(source, external_artist_id) DO UPDATE SET
  albums_json = excluded.albums_json, fetched_at = excluded.fetched_at
`

type UpsertDiscographyCacheParams struct {
	Source           string `json:"source"`
	ExternalArtistID string `json:"external_artist_id"`
	AlbumsJson       string `json:"albums_json"`
	FetchedAt        int64  `json:"fetched_at"`
}

func (q *Queries) UpsertDiscographyCache(ctx context.Context, arg UpsertDiscographyCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertDiscographyCache,
		arg.Source,
		arg.ExternalArtistID,
		arg.AlbumsJson,
		arg.FetchedAt,
	)
	return err
}
