// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: devices.sql

package db

import (
	"context"
)

const createDevice = `-- name: CreateDevice :exec
INSERT INTO device (id, name, token_hash, is_server, created_at, last_seen) VALUES (?, ?, ?, ?, unixepoch(), unixepoch())
`

type CreateDeviceParams struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	IsServer  int64  `json:"is_server"`
}

func (q *Queries) CreateDevice(ctx context.Context, arg CreateDeviceParams) error {
	_, err := q.db.ExecContext(ctx, createDevice,
		arg.ID,
		arg.Name,
		arg.TokenHash,
		arg.IsServer,
	)
	return err
}

const deleteDevice = `-- name: DeleteDevice :exec
DELETE FROM device WHERE id = ?
`

func (q *Queries) DeleteDevice(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDevice, id)
	return err
}

const getDeviceByID = `-- name: GetDeviceByID :one
SELECT id, name, token_hash, is_server, created_at, last_seen FROM device WHERE id = ?
`

func (q *Queries) GetDeviceByID(ctx context.Context, id string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByID, id)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.IsServer,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const getDeviceByTokenHash = `-- name: GetDeviceByTokenHash :one
SELECT id, name, token_hash, is_server, created_at, last_seen FROM device WHERE token_hash = ?
`

func (q *Queries) GetDeviceByTokenHash(ctx context.Context, tokenHash string) (Device, error) {
	row := q.db.QueryRowContext(ctx, getDeviceByTokenHash, tokenHash)
	var i Device
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TokenHash,
		&i.IsServer,
		&i.CreatedAt,
		&i.LastSeen,
	)
	return i, err
}

const listDevices = `-- name: ListDevices :many
SELECT id, name, token_hash, is_server, created_at, last_seen FROM device ORDER BY created_at
`

func (q *Queries) ListDevices(ctx context.Context) ([]Device, error) {
	rows, err := q.db.QueryContext(ctx, listDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Device
	for rows.Next() {
		var i Device
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TokenHash,
			&i.IsServer,
			&i.CreatedAt,
			&i.LastSeen,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchDeviceLastSeen = `-- name: TouchDeviceLastSeen :exec
UPDATE device SET last_seen = unixepoch() WHERE id = ?
`

func (q *Queries) TouchDeviceLastSeen(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchDeviceLastSeen, id)
	return err
}
