// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: download_jobs.sql

package db

import (
	"context"
	"database/sql"
)

const clearMatchedDownloadJobLibraryRefs = `-- name: ClearMatchedDownloadJobLibraryRefs :exec
UPDATE download_jobs SET library_track_id = '', cover_art_id = '' WHERE library_track_id != ''
`

func (q *Queries) ClearMatchedDownloadJobLibraryRefs(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMatchedDownloadJobLibraryRefs)
	return err
}

const deleteDownloadJob = `-- name: DeleteDownloadJob :exec
DELETE FROM download_jobs WHERE id = ?
`

func (q *Queries) DeleteDownloadJob(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteDownloadJob, id)
	return err
}

const deleteFinishedDownloadJobs = `-- name: DeleteFinishedDownloadJobs :many
DELETE FROM download_jobs
WHERE status IN ('completed', 'failed', 'canceled')
RETURNING id
`

func (q *Queries) DeleteFinishedDownloadJobs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, deleteFinishedDownloadJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getActiveDownloadJobByDedup = `-- name: GetActiveDownloadJobByDedup :one
SELECT id, dedup_key, request_json, downloader_name, status, progress, error,
       output_path, library_track_id, cover_art_id, canonical_id, priority, requested_by, attempts,
       downloader_ref, created_at, started_at, finished_at
FROM download_jobs
WHERE dedup_key = ? AND status IN ('queued', 'running')
ORDER BY created_at ASC
LIMIT 1
`

type GetActiveDownloadJobByDedupRow struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	CoverArtID     sql.NullString `json:"cover_art_id"`
	CanonicalID    string         `json:"canonical_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	DownloaderRef  string         `json:"downloader_ref"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) GetActiveDownloadJobByDedup(ctx context.Context, dedupKey string) (GetActiveDownloadJobByDedupRow, error) {
	row := q.db.QueryRowContext(ctx, getActiveDownloadJobByDedup, dedupKey)
	var i GetActiveDownloadJobByDedupRow
	err := row.Scan(
		&i.ID,
		&i.DedupKey,
		&i.RequestJson,
		&i.DownloaderName,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.OutputPath,
		&i.LibraryTrackID,
		&i.CoverArtID,
		&i.CanonicalID,
		&i.Priority,
		&i.RequestedBy,
		&i.Attempts,
		&i.DownloaderRef,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDownloadJob = `-- name: GetDownloadJob :one
SELECT id, dedup_key, request_json, downloader_name, status, progress, error,
       output_path, library_track_id, cover_art_id, canonical_id, priority, requested_by, attempts,
       downloader_ref, created_at, started_at, finished_at
FROM download_jobs WHERE id = ?
`

type GetDownloadJobRow struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	CoverArtID     sql.NullString `json:"cover_art_id"`
	CanonicalID    string         `json:"canonical_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	DownloaderRef  string         `json:"downloader_ref"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) GetDownloadJob(ctx context.Context, id string) (GetDownloadJobRow, error) {
	row := q.db.QueryRowContext(ctx, getDownloadJob, id)
	var i GetDownloadJobRow
	err := row.Scan(
		&i.ID,
		&i.DedupKey,
		&i.RequestJson,
		&i.DownloaderName,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.OutputPath,
		&i.LibraryTrackID,
		&i.CoverArtID,
		&i.CanonicalID,
		&i.Priority,
		&i.RequestedBy,
		&i.Attempts,
		&i.DownloaderRef,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getDownloadJobByDedup = `-- name: GetDownloadJobByDedup :one
SELECT id, dedup_key, request_json, downloader_name, status, progress, error,
       output_path, library_track_id, cover_art_id, canonical_id, priority, requested_by, attempts,
       downloader_ref, created_at, started_at, finished_at
FROM download_jobs
WHERE dedup_key = ?
ORDER BY created_at ASC
LIMIT 1
`

type GetDownloadJobByDedupRow struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	CoverArtID     sql.NullString `json:"cover_art_id"`
	CanonicalID    string         `json:"canonical_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	DownloaderRef  string         `json:"downloader_ref"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) GetDownloadJobByDedup(ctx context.Context, dedupKey string) (GetDownloadJobByDedupRow, error) {
	row := q.db.QueryRowContext(ctx, getDownloadJobByDedup, dedupKey)
	var i GetDownloadJobByDedupRow
	err := row.Scan(
		&i.ID,
		&i.DedupKey,
		&i.RequestJson,
		&i.DownloaderName,
		&i.Status,
		&i.Progress,
		&i.Error,
		&i.OutputPath,
		&i.LibraryTrackID,
		&i.CoverArtID,
		&i.CanonicalID,
		&i.Priority,
		&i.RequestedBy,
		&i.Attempts,
		&i.DownloaderRef,
		&i.CreatedAt,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const incrementDownloadJobAttempts = `-- name: IncrementDownloadJobAttempts :exec
UPDATE download_jobs SET attempts = attempts + 1 WHERE id = ?
`

func (q *Queries) IncrementDownloadJobAttempts(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, incrementDownloadJobAttempts, id)
	return err
}

const insertDownloadJob = `-- name: InsertDownloadJob :exec
INSERT INTO download_jobs (
    id, dedup_key, request_json, downloader_name, status, progress, error,
    output_path, library_track_id, priority, requested_by, attempts, downloader_ref,
    initiated_by, created_at, started_at, finished_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, unixepoch(), NULL, NULL)
`

type InsertDownloadJobParams struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	DownloaderRef  string         `json:"downloader_ref"`
	InitiatedBy    sql.NullString `json:"initiated_by"`
}

func (q *Queries) InsertDownloadJob(ctx context.Context, arg InsertDownloadJobParams) error {
	_, err := q.db.ExecContext(ctx, insertDownloadJob,
		arg.ID,
		arg.DedupKey,
		arg.RequestJson,
		arg.DownloaderName,
		arg.Status,
		arg.Progress,
		arg.Error,
		arg.OutputPath,
		arg.LibraryTrackID,
		arg.Priority,
		arg.RequestedBy,
		arg.Attempts,
		arg.DownloaderRef,
		arg.InitiatedBy,
	)
	return err
}

const listDownloadJobs = `-- name: ListDownloadJobs :many
SELECT id, dedup_key, request_json, downloader_name, status, progress, error,
       output_path, library_track_id, cover_art_id, canonical_id, priority, requested_by, attempts,
       downloader_ref, created_at, started_at, finished_at
FROM download_jobs
ORDER BY created_at DESC
`

type ListDownloadJobsRow struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	CoverArtID     sql.NullString `json:"cover_art_id"`
	CanonicalID    string         `json:"canonical_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	DownloaderRef  string         `json:"downloader_ref"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) ListDownloadJobs(ctx context.Context) ([]ListDownloadJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDownloadJobsRow
	for rows.Next() {
		var i ListDownloadJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.DedupKey,
			&i.RequestJson,
			&i.DownloaderName,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.OutputPath,
			&i.LibraryTrackID,
			&i.CoverArtID,
			&i.CanonicalID,
			&i.Priority,
			&i.RequestedBy,
			&i.Attempts,
			&i.DownloaderRef,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadJobsByStatus = `-- name: ListDownloadJobsByStatus :many
SELECT id, dedup_key, request_json, downloader_name, status, progress, error,
       output_path, library_track_id, cover_art_id, canonical_id, priority, requested_by, attempts,
       downloader_ref, created_at, started_at, finished_at
FROM download_jobs
WHERE status = ?
ORDER BY created_at DESC
`

type ListDownloadJobsByStatusRow struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	CoverArtID     sql.NullString `json:"cover_art_id"`
	CanonicalID    string         `json:"canonical_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	DownloaderRef  string         `json:"downloader_ref"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
}

func (q *Queries) ListDownloadJobsByStatus(ctx context.Context, status string) ([]ListDownloadJobsByStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadJobsByStatus, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDownloadJobsByStatusRow
	for rows.Next() {
		var i ListDownloadJobsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.DedupKey,
			&i.RequestJson,
			&i.DownloaderName,
			&i.Status,
			&i.Progress,
			&i.Error,
			&i.OutputPath,
			&i.LibraryTrackID,
			&i.CoverArtID,
			&i.CanonicalID,
			&i.Priority,
			&i.RequestedBy,
			&i.Attempts,
			&i.DownloaderRef,
			&i.CreatedAt,
			&i.StartedAt,
			&i.FinishedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointDownloadJobs = `-- name: RepointDownloadJobs :exec
UPDATE download_jobs SET canonical_id = ?1 WHERE canonical_id = ?2
`

type RepointDownloadJobsParams struct {
	CanonicalID  string `json:"canonical_id"`
	CanonicalID2 string `json:"canonical_id_2"`
}

func (q *Queries) RepointDownloadJobs(ctx context.Context, arg RepointDownloadJobsParams) error {
	_, err := q.db.ExecContext(ctx, repointDownloadJobs, arg.CanonicalID, arg.CanonicalID2)
	return err
}

const updateDownloadJobCanonicalID = `-- name: UpdateDownloadJobCanonicalID :exec
UPDATE download_jobs SET canonical_id = ?1 WHERE id = ?2
`

type UpdateDownloadJobCanonicalIDParams struct {
	CanonicalID string `json:"canonical_id"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateDownloadJobCanonicalID(ctx context.Context, arg UpdateDownloadJobCanonicalIDParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobCanonicalID, arg.CanonicalID, arg.ID)
	return err
}

const updateDownloadJobCoverArtID = `-- name: UpdateDownloadJobCoverArtID :exec
UPDATE download_jobs SET cover_art_id = ? WHERE id = ?
`

type UpdateDownloadJobCoverArtIDParams struct {
	CoverArtID sql.NullString `json:"cover_art_id"`
	ID         string         `json:"id"`
}

func (q *Queries) UpdateDownloadJobCoverArtID(ctx context.Context, arg UpdateDownloadJobCoverArtIDParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobCoverArtID, arg.CoverArtID, arg.ID)
	return err
}

const updateDownloadJobError = `-- name: UpdateDownloadJobError :exec
UPDATE download_jobs SET error = ? WHERE id = ?
`

type UpdateDownloadJobErrorParams struct {
	Error string `json:"error"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateDownloadJobError(ctx context.Context, arg UpdateDownloadJobErrorParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobError, arg.Error, arg.ID)
	return err
}

const updateDownloadJobLibraryTrackID = `-- name: UpdateDownloadJobLibraryTrackID :exec
UPDATE download_jobs SET library_track_id = ? WHERE id = ?
`

type UpdateDownloadJobLibraryTrackIDParams struct {
	LibraryTrackID sql.NullString `json:"library_track_id"`
	ID             string         `json:"id"`
}

func (q *Queries) UpdateDownloadJobLibraryTrackID(ctx context.Context, arg UpdateDownloadJobLibraryTrackIDParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobLibraryTrackID, arg.LibraryTrackID, arg.ID)
	return err
}

const updateDownloadJobOutputPath = `-- name: UpdateDownloadJobOutputPath :exec
UPDATE download_jobs SET output_path = ? WHERE id = ?
`

type UpdateDownloadJobOutputPathParams struct {
	OutputPath string `json:"output_path"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateDownloadJobOutputPath(ctx context.Context, arg UpdateDownloadJobOutputPathParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobOutputPath, arg.OutputPath, arg.ID)
	return err
}

const updateDownloadJobProgress = `-- name: UpdateDownloadJobProgress :exec
UPDATE download_jobs SET progress = ? WHERE id = ?
`

type UpdateDownloadJobProgressParams struct {
	Progress int64  `json:"progress"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateDownloadJobProgress(ctx context.Context, arg UpdateDownloadJobProgressParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobProgress, arg.Progress, arg.ID)
	return err
}

const updateDownloadJobRef = `-- name: UpdateDownloadJobRef :exec
UPDATE download_jobs SET downloader_ref = ? WHERE id = ?
`

type UpdateDownloadJobRefParams struct {
	DownloaderRef string `json:"downloader_ref"`
	ID            string `json:"id"`
}

func (q *Queries) UpdateDownloadJobRef(ctx context.Context, arg UpdateDownloadJobRefParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobRef, arg.DownloaderRef, arg.ID)
	return err
}

const updateDownloadJobRequestJson = `-- name: UpdateDownloadJobRequestJson :exec
UPDATE download_jobs SET request_json = ? WHERE id = ?
`

type UpdateDownloadJobRequestJsonParams struct {
	RequestJson string `json:"request_json"`
	ID          string `json:"id"`
}

func (q *Queries) UpdateDownloadJobRequestJson(ctx context.Context, arg UpdateDownloadJobRequestJsonParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobRequestJson, arg.RequestJson, arg.ID)
	return err
}

const updateDownloadJobStatus = `-- name: UpdateDownloadJobStatus :exec
UPDATE download_jobs
SET status     = ?1,
    started_at  = CASE WHEN ?1 = 'running' AND started_at IS NULL THEN unixepoch() ELSE started_at END,
    finished_at = CASE WHEN ?1 = 'completed' OR ?1 = 'failed' OR ?1 = 'canceled' THEN unixepoch() ELSE finished_at END
WHERE id = ?2
`

type UpdateDownloadJobStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateDownloadJobStatus(ctx context.Context, arg UpdateDownloadJobStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateDownloadJobStatus, arg.Status, arg.ID)
	return err
}
