// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: entity_overrides.sql

package db

import (
	"context"
)

const countEntityCoverRefs = `-- name: CountEntityCoverRefs :one
SELECT COUNT(*) FROM entity_cover WHERE sha256 = ?
`

func (q *Queries) CountEntityCoverRefs(ctx context.Context, sha256 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countEntityCoverRefs, sha256)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteEntityCover = `-- name: DeleteEntityCover :exec
DELETE FROM entity_cover WHERE entity_type = ? AND entity_id = ?
`

type DeleteEntityCoverParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) DeleteEntityCover(ctx context.Context, arg DeleteEntityCoverParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntityCover, arg.EntityType, arg.EntityID)
	return err
}

const deleteEntityCoverByKey = `-- name: DeleteEntityCoverByKey :exec
DELETE FROM entity_cover WHERE entity_type = ? AND entity_key = ?
`

type DeleteEntityCoverByKeyParams struct {
	EntityType string `json:"entity_type"`
	EntityKey  string `json:"entity_key"`
}

func (q *Queries) DeleteEntityCoverByKey(ctx context.Context, arg DeleteEntityCoverByKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntityCoverByKey, arg.EntityType, arg.EntityKey)
	return err
}

const deleteEntityOverride = `-- name: DeleteEntityOverride :exec
DELETE FROM entity_override WHERE entity_type = ? AND entity_id = ?
`

type DeleteEntityOverrideParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) DeleteEntityOverride(ctx context.Context, arg DeleteEntityOverrideParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntityOverride, arg.EntityType, arg.EntityID)
	return err
}

const deleteEntityOverrideByKey = `-- name: DeleteEntityOverrideByKey :exec
DELETE FROM entity_override WHERE entity_type = ? AND entity_key = ?
`

type DeleteEntityOverrideByKeyParams struct {
	EntityType string `json:"entity_type"`
	EntityKey  string `json:"entity_key"`
}

func (q *Queries) DeleteEntityOverrideByKey(ctx context.Context, arg DeleteEntityOverrideByKeyParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntityOverrideByKey, arg.EntityType, arg.EntityKey)
	return err
}

const getEntityCover = `-- name: GetEntityCover :one
SELECT entity_type, entity_id, entity_key, sha256, ext, updated_at FROM entity_cover WHERE entity_type = ? AND entity_id = ?
`

type GetEntityCoverParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) GetEntityCover(ctx context.Context, arg GetEntityCoverParams) (EntityCover, error) {
	row := q.db.QueryRowContext(ctx, getEntityCover, arg.EntityType, arg.EntityID)
	var i EntityCover
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.EntityKey,
		&i.Sha256,
		&i.Ext,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityCoverByKey = `-- name: GetEntityCoverByKey :one
SELECT entity_type, entity_id, entity_key, sha256, ext, updated_at FROM entity_cover WHERE entity_type = ? AND entity_key = ? LIMIT 1
`

type GetEntityCoverByKeyParams struct {
	EntityType string `json:"entity_type"`
	EntityKey  string `json:"entity_key"`
}

func (q *Queries) GetEntityCoverByKey(ctx context.Context, arg GetEntityCoverByKeyParams) (EntityCover, error) {
	row := q.db.QueryRowContext(ctx, getEntityCoverByKey, arg.EntityType, arg.EntityKey)
	var i EntityCover
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.EntityKey,
		&i.Sha256,
		&i.Ext,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityOverride = `-- name: GetEntityOverride :one
SELECT entity_type, entity_id, entity_key, name, updated_at FROM entity_override WHERE entity_type = ? AND entity_id = ?
`

type GetEntityOverrideParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
}

func (q *Queries) GetEntityOverride(ctx context.Context, arg GetEntityOverrideParams) (EntityOverride, error) {
	row := q.db.QueryRowContext(ctx, getEntityOverride, arg.EntityType, arg.EntityID)
	var i EntityOverride
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.EntityKey,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const getEntityOverrideByKey = `-- name: GetEntityOverrideByKey :one
SELECT entity_type, entity_id, entity_key, name, updated_at FROM entity_override WHERE entity_type = ? AND entity_key = ? LIMIT 1
`

type GetEntityOverrideByKeyParams struct {
	EntityType string `json:"entity_type"`
	EntityKey  string `json:"entity_key"`
}

func (q *Queries) GetEntityOverrideByKey(ctx context.Context, arg GetEntityOverrideByKeyParams) (EntityOverride, error) {
	row := q.db.QueryRowContext(ctx, getEntityOverrideByKey, arg.EntityType, arg.EntityKey)
	var i EntityOverride
	err := row.Scan(
		&i.EntityType,
		&i.EntityID,
		&i.EntityKey,
		&i.Name,
		&i.UpdatedAt,
	)
	return i, err
}

const listEntityCovers = `-- name: ListEntityCovers :many
SELECT entity_type, entity_id, entity_key, sha256, ext, updated_at FROM entity_cover
`

func (q *Queries) ListEntityCovers(ctx context.Context) ([]EntityCover, error) {
	rows, err := q.db.QueryContext(ctx, listEntityCovers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityCover
	for rows.Next() {
		var i EntityCover
		if err := rows.Scan(
			&i.EntityType,
			&i.EntityID,
			&i.EntityKey,
			&i.Sha256,
			&i.Ext,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEntityOverrides = `-- name: ListEntityOverrides :many
SELECT entity_type, entity_id, entity_key, name, updated_at FROM entity_override WHERE entity_type = ?
`

func (q *Queries) ListEntityOverrides(ctx context.Context, entityType string) ([]EntityOverride, error) {
	rows, err := q.db.QueryContext(ctx, listEntityOverrides, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityOverride
	for rows.Next() {
		var i EntityOverride
		if err := rows.Scan(
			&i.EntityType,
			&i.EntityID,
			&i.EntityKey,
			&i.Name,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointEntityCoverKey = `-- name: RepointEntityCoverKey :exec
UPDATE entity_cover SET entity_key = ? WHERE entity_type = ? AND entity_key = ?
`

type RepointEntityCoverKeyParams struct {
	EntityKey   string `json:"entity_key"`
	EntityType  string `json:"entity_type"`
	EntityKey_2 string `json:"entity_key_2"`
}

func (q *Queries) RepointEntityCoverKey(ctx context.Context, arg RepointEntityCoverKeyParams) error {
	_, err := q.db.ExecContext(ctx, repointEntityCoverKey, arg.EntityKey, arg.EntityType, arg.EntityKey_2)
	return err
}

const upsertEntityCover = `-- name: UpsertEntityCover :exec
INSERT INTO entity_cover (entity_type, entity_id, entity_key, sha256, ext, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(entity_type, entity_id) DO UPDATE SET
  entity_key = excluded.entity_key,
  sha256 = excluded.sha256,
  ext = excluded.ext,
  updated_at = excluded.updated_at
`

type UpsertEntityCoverParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	EntityKey  string `json:"entity_key"`
	Sha256     string `json:"sha256"`
	Ext        string `json:"ext"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) UpsertEntityCover(ctx context.Context, arg UpsertEntityCoverParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntityCover,
		arg.EntityType,
		arg.EntityID,
		arg.EntityKey,
		arg.Sha256,
		arg.Ext,
		arg.UpdatedAt,
	)
	return err
}

const upsertEntityOverride = `-- name: UpsertEntityOverride :exec
INSERT INTO entity_override (entity_type, entity_id, entity_key, name, updated_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(entity_type, entity_id) DO UPDATE SET
  entity_key = excluded.entity_key,
  name = excluded.name,
  updated_at = excluded.updated_at
`

type UpsertEntityOverrideParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	EntityKey  string `json:"entity_key"`
	Name       string `json:"name"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) UpsertEntityOverride(ctx context.Context, arg UpsertEntityOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertEntityOverride,
		arg.EntityType,
		arg.EntityID,
		arg.EntityKey,
		arg.Name,
		arg.UpdatedAt,
	)
	return err
}
