// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: extstream_resolve.sql

package db

import (
	"context"
)

const clearExtstreamURL = `-- name: ClearExtstreamURL :exec
UPDATE extstream_resolve SET url = '', url_expires_at = 0, updated_at = ?
WHERE source = ? AND external_id = ?
`

type ClearExtstreamURLParams struct {
	UpdatedAt  int64  `json:"updated_at"`
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

// Drops a URL the upstream rejected, keeping the video id that is still good.
func (q *Queries) ClearExtstreamURL(ctx context.Context, arg ClearExtstreamURLParams) error {
	_, err := q.db.ExecContext(ctx, clearExtstreamURL, arg.UpdatedAt, arg.Source, arg.ExternalID)
	return err
}

const getExtstreamResolve = `-- name: GetExtstreamResolve :one
SELECT source, external_id, video_id, url, url_expires_at, updated_at FROM extstream_resolve WHERE source = ? AND external_id = ?
`

type GetExtstreamResolveParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetExtstreamResolve(ctx context.Context, arg GetExtstreamResolveParams) (ExtstreamResolve, error) {
	row := q.db.QueryRowContext(ctx, getExtstreamResolve, arg.Source, arg.ExternalID)
	var i ExtstreamResolve
	err := row.Scan(
		&i.Source,
		&i.ExternalID,
		&i.VideoID,
		&i.Url,
		&i.UrlExpiresAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertExtstreamURL = `-- name: UpsertExtstreamURL :exec
INSERT INTO extstream_resolve (source, external_id, video_id, url, url_expires_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(source, external_id) DO UPDATE SET
  video_id = excluded.video_id,
  url = excluded.url,
  url_expires_at = excluded.url_expires_at,
  updated_at = excluded.updated_at
`

type UpsertExtstreamURLParams struct {
	Source       string `json:"source"`
	ExternalID   string `json:"external_id"`
	VideoID      string `json:"video_id"`
	Url          string `json:"url"`
	UrlExpiresAt int64  `json:"url_expires_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

func (q *Queries) UpsertExtstreamURL(ctx context.Context, arg UpsertExtstreamURLParams) error {
	_, err := q.db.ExecContext(ctx, upsertExtstreamURL,
		arg.Source,
		arg.ExternalID,
		arg.VideoID,
		arg.Url,
		arg.UrlExpiresAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertExtstreamVideoID = `-- name: UpsertExtstreamVideoID :exec
INSERT INTO extstream_resolve (source, external_id, video_id, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(source, external_id) DO UPDATE SET
  video_id = excluded.video_id,
  updated_at = excluded.updated_at
`

type UpsertExtstreamVideoIDParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
	VideoID    string `json:"video_id"`
	UpdatedAt  int64  `json:"updated_at"`
}

// Records which upstream track this is. Leaves any still-valid URL alone: the
// search answer changing does not invalidate a URL already fetched for it.
func (q *Queries) UpsertExtstreamVideoID(ctx context.Context, arg UpsertExtstreamVideoIDParams) error {
	_, err := q.db.ExecContext(ctx, upsertExtstreamVideoID,
		arg.Source,
		arg.ExternalID,
		arg.VideoID,
		arg.UpdatedAt,
	)
	return err
}
