// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file_fetch_failure.sql

package db

import (
	"context"
)

const deleteFileFetchFailure = `-- name: DeleteFileFetchFailure :exec
DELETE FROM file_fetch_failure WHERE peer_id = ? AND content_hash = ?
`

type DeleteFileFetchFailureParams struct {
	PeerID      string `json:"peer_id"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) DeleteFileFetchFailure(ctx context.Context, arg DeleteFileFetchFailureParams) error {
	_, err := q.db.ExecContext(ctx, deleteFileFetchFailure, arg.PeerID, arg.ContentHash)
	return err
}

const getFileFetchFailure = `-- name: GetFileFetchFailure :one
SELECT peer_id, content_hash, rel_path, reason, detail, attempts, first_failed_at, last_failed_at, next_attempt_at FROM file_fetch_failure WHERE peer_id = ? AND content_hash = ?
`

type GetFileFetchFailureParams struct {
	PeerID      string `json:"peer_id"`
	ContentHash string `json:"content_hash"`
}

func (q *Queries) GetFileFetchFailure(ctx context.Context, arg GetFileFetchFailureParams) (FileFetchFailure, error) {
	row := q.db.QueryRowContext(ctx, getFileFetchFailure, arg.PeerID, arg.ContentHash)
	var i FileFetchFailure
	err := row.Scan(
		&i.PeerID,
		&i.ContentHash,
		&i.RelPath,
		&i.Reason,
		&i.Detail,
		&i.Attempts,
		&i.FirstFailedAt,
		&i.LastFailedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const listFileFetchFailures = `-- name: ListFileFetchFailures :many
SELECT peer_id, content_hash, rel_path, reason, detail, attempts, first_failed_at, last_failed_at, next_attempt_at FROM file_fetch_failure ORDER BY last_failed_at DESC
`

func (q *Queries) ListFileFetchFailures(ctx context.Context) ([]FileFetchFailure, error) {
	rows, err := q.db.QueryContext(ctx, listFileFetchFailures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileFetchFailure
	for rows.Next() {
		var i FileFetchFailure
		if err := rows.Scan(
			&i.PeerID,
			&i.ContentHash,
			&i.RelPath,
			&i.Reason,
			&i.Detail,
			&i.Attempts,
			&i.FirstFailedAt,
			&i.LastFailedAt,
			&i.NextAttemptAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFileFetchFailure = `-- name: UpsertFileFetchFailure :exec
INSERT INTO file_fetch_failure (peer_id, content_hash, rel_path, reason, detail, attempts, first_failed_at, last_failed_at, next_attempt_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(peer_id, content_hash) DO UPDATE SET
  rel_path = excluded.rel_path,
  reason = excluded.reason,
  detail = excluded.detail,
  attempts = excluded.attempts,
  last_failed_at = excluded.last_failed_at,
  next_attempt_at = excluded.next_attempt_at
`

type UpsertFileFetchFailureParams struct {
	PeerID        string `json:"peer_id"`
	ContentHash   string `json:"content_hash"`
	RelPath       string `json:"rel_path"`
	Reason        string `json:"reason"`
	Detail        string `json:"detail"`
	Attempts      int64  `json:"attempts"`
	FirstFailedAt int64  `json:"first_failed_at"`
	LastFailedAt  int64  `json:"last_failed_at"`
	NextAttemptAt int64  `json:"next_attempt_at"`
}

func (q *Queries) UpsertFileFetchFailure(ctx context.Context, arg UpsertFileFetchFailureParams) error {
	_, err := q.db.ExecContext(ctx, upsertFileFetchFailure,
		arg.PeerID,
		arg.ContentHash,
		arg.RelPath,
		arg.Reason,
		arg.Detail,
		arg.Attempts,
		arg.FirstFailedAt,
		arg.LastFailedAt,
		arg.NextAttemptAt,
	)
	return err
}
