// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: file_manifest.sql

package db

import (
	"context"
)

const countFileManifests = `-- name: CountFileManifests :one
SELECT COUNT(*) FROM file_manifest
`

func (q *Queries) CountFileManifests(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFileManifests)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteFileManifest = `-- name: DeleteFileManifest :exec
DELETE FROM file_manifest WHERE canonical_id = ?
`

func (q *Queries) DeleteFileManifest(ctx context.Context, canonicalID string) error {
	_, err := q.db.ExecContext(ctx, deleteFileManifest, canonicalID)
	return err
}

const deleteOrphanFileTags = `-- name: DeleteOrphanFileTags :exec
DELETE FROM file_tag WHERE content_hash NOT IN (SELECT content_hash FROM file_manifest)
`

func (q *Queries) DeleteOrphanFileTags(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteOrphanFileTags)
	return err
}

const getFileManifest = `-- name: GetFileManifest :one
SELECT canonical_id, content_hash, size, rel_path, mtime, device_id FROM file_manifest WHERE canonical_id = ?
`

func (q *Queries) GetFileManifest(ctx context.Context, canonicalID string) (FileManifest, error) {
	row := q.db.QueryRowContext(ctx, getFileManifest, canonicalID)
	var i FileManifest
	err := row.Scan(
		&i.CanonicalID,
		&i.ContentHash,
		&i.Size,
		&i.RelPath,
		&i.Mtime,
		&i.DeviceID,
	)
	return i, err
}

const listFileManifests = `-- name: ListFileManifests :many
SELECT canonical_id, content_hash, size, rel_path, mtime, device_id FROM file_manifest ORDER BY canonical_id
`

func (q *Queries) ListFileManifests(ctx context.Context) ([]FileManifest, error) {
	rows, err := q.db.QueryContext(ctx, listFileManifests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileManifest
	for rows.Next() {
		var i FileManifest
		if err := rows.Scan(
			&i.CanonicalID,
			&i.ContentHash,
			&i.Size,
			&i.RelPath,
			&i.Mtime,
			&i.DeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileManifestsByHash = `-- name: ListFileManifestsByHash :many
SELECT canonical_id, content_hash, size, rel_path, mtime, device_id FROM file_manifest WHERE content_hash = ?
`

func (q *Queries) ListFileManifestsByHash(ctx context.Context, contentHash string) ([]FileManifest, error) {
	rows, err := q.db.QueryContext(ctx, listFileManifestsByHash, contentHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileManifest
	for rows.Next() {
		var i FileManifest
		if err := rows.Scan(
			&i.CanonicalID,
			&i.ContentHash,
			&i.Size,
			&i.RelPath,
			&i.Mtime,
			&i.DeviceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileTags = `-- name: ListFileTags :many
SELECT content_hash, title, artist, album, isrc FROM file_tag
`

func (q *Queries) ListFileTags(ctx context.Context) ([]FileTag, error) {
	rows, err := q.db.QueryContext(ctx, listFileTags)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FileTag
	for rows.Next() {
		var i FileTag
		if err := rows.Scan(
			&i.ContentHash,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Isrc,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertFileManifest = `-- name: UpsertFileManifest :exec
INSERT INTO file_manifest (canonical_id, content_hash, size, rel_path, mtime, device_id) VALUES (?, ?, ?, ?, ?, ?) ON CONFLICT(canonical_id) DO UPDATE SET content_hash = excluded.content_hash, size = excluded.size, rel_path = excluded.rel_path, mtime = excluded.mtime, device_id = excluded.device_id
`

type UpsertFileManifestParams struct {
	CanonicalID string `json:"canonical_id"`
	ContentHash string `json:"content_hash"`
	Size        int64  `json:"size"`
	RelPath     string `json:"rel_path"`
	Mtime       int64  `json:"mtime"`
	DeviceID    string `json:"device_id"`
}

func (q *Queries) UpsertFileManifest(ctx context.Context, arg UpsertFileManifestParams) error {
	_, err := q.db.ExecContext(ctx, upsertFileManifest,
		arg.CanonicalID,
		arg.ContentHash,
		arg.Size,
		arg.RelPath,
		arg.Mtime,
		arg.DeviceID,
	)
	return err
}

const upsertFileTag = `-- name: UpsertFileTag :exec
INSERT INTO file_tag (content_hash, title, artist, album, isrc) VALUES (?, ?, ?, ?, ?) ON CONFLICT(content_hash) DO UPDATE SET title = excluded.title, artist = excluded.artist, album = excluded.album, isrc = excluded.isrc
`

type UpsertFileTagParams struct {
	ContentHash string `json:"content_hash"`
	Title       string `json:"title"`
	Artist      string `json:"artist"`
	Album       string `json:"album"`
	Isrc        string `json:"isrc"`
}

func (q *Queries) UpsertFileTag(ctx context.Context, arg UpsertFileTagParams) error {
	_, err := q.db.ExecContext(ctx, upsertFileTag,
		arg.ContentHash,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.Isrc,
	)
	return err
}
