// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: library_version.sql

package db

import (
	"context"
)

const getLibraryVersion = `-- name: GetLibraryVersion :one
SELECT value FROM settings WHERE key = 'library_version'
`

func (q *Queries) GetLibraryVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getLibraryVersion)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setLibraryVersion = `-- name: SetLibraryVersion :exec
INSERT INTO settings (key, value) VALUES ('library_version', ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

func (q *Queries) SetLibraryVersion(ctx context.Context, value string) error {
	_, err := q.db.ExecContext(ctx, setLibraryVersion, value)
	return err
}
