// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: lyrics.sql

package db

import (
	"context"
)

const getLyrics = `-- name: GetLyrics :one
SELECT track_key, synced, body, source, fetched_at FROM lyrics WHERE track_key = ?
`

func (q *Queries) GetLyrics(ctx context.Context, trackKey string) (Lyric, error) {
	row := q.db.QueryRowContext(ctx, getLyrics, trackKey)
	var i Lyric
	err := row.Scan(
		&i.TrackKey,
		&i.Synced,
		&i.Body,
		&i.Source,
		&i.FetchedAt,
	)
	return i, err
}

const upsertLyrics = `-- name: UpsertLyrics :exec
INSERT INTO lyrics (track_key, synced, body, source, fetched_at)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(track_key) DO UPDATE SET
  synced = excluded.synced,
  body = excluded.body,
  source = excluded.source,
  fetched_at = excluded.fetched_at
`

type UpsertLyricsParams struct {
	TrackKey  string `json:"track_key"`
	Synced    int64  `json:"synced"`
	Body      string `json:"body"`
	Source    string `json:"source"`
	FetchedAt int64  `json:"fetched_at"`
}

func (q *Queries) UpsertLyrics(ctx context.Context, arg UpsertLyricsParams) error {
	_, err := q.db.ExecContext(ctx, upsertLyrics,
		arg.TrackKey,
		arg.Synced,
		arg.Body,
		arg.Source,
		arg.FetchedAt,
	)
	return err
}
