// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: match_cache.sql

package db

import (
	"context"
	"database/sql"
)

const clearMatchCache = `-- name: ClearMatchCache :exec
DELETE FROM match_cache
`

func (q *Queries) ClearMatchCache(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, clearMatchCache)
	return err
}

const deleteMatchCacheBySource = `-- name: DeleteMatchCacheBySource :exec
DELETE FROM match_cache WHERE source = ?
`

func (q *Queries) DeleteMatchCacheBySource(ctx context.Context, source string) error {
	_, err := q.db.ExecContext(ctx, deleteMatchCacheBySource, source)
	return err
}

const getMatchCache = `-- name: GetMatchCache :one
SELECT source, external_id, library_track_id, method, confidence, isrc, mbid, duration_ms, library_version, matched_at, artist_id, album_id, cover_art_id
FROM match_cache
WHERE source = ? AND external_id = ?
`

type GetMatchCacheParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetMatchCache(ctx context.Context, arg GetMatchCacheParams) (MatchCache, error) {
	row := q.db.QueryRowContext(ctx, getMatchCache, arg.Source, arg.ExternalID)
	var i MatchCache
	err := row.Scan(
		&i.Source,
		&i.ExternalID,
		&i.LibraryTrackID,
		&i.Method,
		&i.Confidence,
		&i.Isrc,
		&i.Mbid,
		&i.DurationMs,
		&i.LibraryVersion,
		&i.MatchedAt,
		&i.ArtistID,
		&i.AlbumID,
		&i.CoverArtID,
	)
	return i, err
}

const upsertMatchCache = `-- name: UpsertMatchCache :exec
INSERT INTO match_cache (
    source, external_id, library_track_id, method, confidence, isrc, mbid, duration_ms, library_version, matched_at, artist_id, album_id, cover_art_id
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, unixepoch(), ?, ?, ?)
ON CONFLICT(source, external_id) DO UPDATE SET
    library_track_id = excluded.library_track_id,
    method           = excluded.method,
    confidence       = excluded.confidence,
    isrc             = excluded.isrc,
    mbid             = excluded.mbid,
    duration_ms      = excluded.duration_ms,
    library_version  = excluded.library_version,
    matched_at       = excluded.matched_at,
    artist_id        = excluded.artist_id,
    album_id         = excluded.album_id,
    cover_art_id     = excluded.cover_art_id
`

type UpsertMatchCacheParams struct {
	Source         string         `json:"source"`
	ExternalID     string         `json:"external_id"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	Method         string         `json:"method"`
	Confidence     float64        `json:"confidence"`
	Isrc           string         `json:"isrc"`
	Mbid           string         `json:"mbid"`
	DurationMs     int64          `json:"duration_ms"`
	LibraryVersion int64          `json:"library_version"`
	ArtistID       string         `json:"artist_id"`
	AlbumID        string         `json:"album_id"`
	CoverArtID     string         `json:"cover_art_id"`
}

func (q *Queries) UpsertMatchCache(ctx context.Context, arg UpsertMatchCacheParams) error {
	_, err := q.db.ExecContext(ctx, upsertMatchCache,
		arg.Source,
		arg.ExternalID,
		arg.LibraryTrackID,
		arg.Method,
		arg.Confidence,
		arg.Isrc,
		arg.Mbid,
		arg.DurationMs,
		arg.LibraryVersion,
		arg.ArtistID,
		arg.AlbumID,
		arg.CoverArtID,
	)
	return err
}
