// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
)

type AdapterInstance struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Name       string `json:"name"`
	Enabled    int64  `json:"enabled"`
	Priority   int64  `json:"priority"`
	ConfigJson string `json:"config_json"`
	CreatedAt  int64  `json:"created_at"`
	UpdatedAt  int64  `json:"updated_at"`
}

type AlbumCoverage struct {
	Source          string `json:"source"`
	ExternalAlbumID string `json:"external_album_id"`
	CoverageJson    string `json:"coverage_json"`
	LibraryAlbumID  string `json:"library_album_id"`
	FetchedAt       int64  `json:"fetched_at"`
	LibraryVersion  int64  `json:"library_version"`
}

type AlbumExternalMap struct {
	LibraryAlbumID  string  `json:"library_album_id"`
	Source          string  `json:"source"`
	ExternalAlbumID string  `json:"external_album_id"`
	Confidence      float64 `json:"confidence"`
	CreatedAt       int64   `json:"created_at"`
}

type ArtistExternalMap struct {
	LibraryArtistID  string  `json:"library_artist_id"`
	Source           string  `json:"source"`
	ExternalArtistID string  `json:"external_artist_id"`
	Confidence       float64 `json:"confidence"`
	CreatedAt        int64   `json:"created_at"`
}

type BackendBinding struct {
	CatalogID       string `json:"catalog_id"`
	LibraryIdentity string `json:"library_identity"`
	BackendID       string `json:"backend_id"`
	CoverArtID      string `json:"cover_art_id"`
	KnownAbsent     int64  `json:"known_absent"`
	BindingEpoch    int64  `json:"binding_epoch"`
	ResolvedAt      int64  `json:"resolved_at"`
}

type CatalogAlias struct {
	AliasKind  string `json:"alias_kind"`
	AliasValue string `json:"alias_value"`
	CatalogID  string `json:"catalog_id"`
	CreatedAt  int64  `json:"created_at"`
}

type CatalogEntity struct {
	ID         string `json:"id"`
	Kind       string `json:"kind"`
	Title      string `json:"title"`
	Artist     string `json:"artist"`
	Album      string `json:"album"`
	DurationMs int64  `json:"duration_ms"`
	Isrc       string `json:"isrc"`
	Mbid       string `json:"mbid"`
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
	CreatedAt  int64  `json:"created_at"`
}

type Device struct {
	ID        string `json:"id"`
	Name      string `json:"name"`
	TokenHash string `json:"token_hash"`
	IsServer  int64  `json:"is_server"`
	CreatedAt int64  `json:"created_at"`
	LastSeen  int64  `json:"last_seen"`
	PublicKey string `json:"public_key"`
}

type DiscographyCache struct {
	Source           string `json:"source"`
	ExternalArtistID string `json:"external_artist_id"`
	AlbumsJson       string `json:"albums_json"`
	FetchedAt        int64  `json:"fetched_at"`
}

type DownloadJob struct {
	ID             string         `json:"id"`
	DedupKey       string         `json:"dedup_key"`
	RequestJson    string         `json:"request_json"`
	DownloaderName string         `json:"downloader_name"`
	Status         string         `json:"status"`
	Progress       int64          `json:"progress"`
	Error          string         `json:"error"`
	OutputPath     string         `json:"output_path"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	Priority       int64          `json:"priority"`
	RequestedBy    sql.NullString `json:"requested_by"`
	Attempts       int64          `json:"attempts"`
	CreatedAt      int64          `json:"created_at"`
	StartedAt      sql.NullInt64  `json:"started_at"`
	FinishedAt     sql.NullInt64  `json:"finished_at"`
	CoverArtID     sql.NullString `json:"cover_art_id"`
	DownloaderRef  string         `json:"downloader_ref"`
	InitiatedBy    sql.NullString `json:"initiated_by"`
	CanonicalID    string         `json:"canonical_id"`
}

type ExtstreamResolve struct {
	Source       string `json:"source"`
	ExternalID   string `json:"external_id"`
	VideoID      string `json:"video_id"`
	Url          string `json:"url"`
	UrlExpiresAt int64  `json:"url_expires_at"`
	UpdatedAt    int64  `json:"updated_at"`
}

type FileManifest struct {
	CanonicalID string `json:"canonical_id"`
	ContentHash string `json:"content_hash"`
	Size        int64  `json:"size"`
	RelPath     string `json:"rel_path"`
	Mtime       int64  `json:"mtime"`
	DeviceID    string `json:"device_id"`
}

type Lyric struct {
	TrackKey  string `json:"track_key"`
	Synced    int64  `json:"synced"`
	Body      string `json:"body"`
	Source    string `json:"source"`
	FetchedAt int64  `json:"fetched_at"`
}

type MatchCache struct {
	Source         string         `json:"source"`
	ExternalID     string         `json:"external_id"`
	LibraryTrackID sql.NullString `json:"library_track_id"`
	Method         string         `json:"method"`
	Confidence     float64        `json:"confidence"`
	Isrc           string         `json:"isrc"`
	Mbid           string         `json:"mbid"`
	DurationMs     int64          `json:"duration_ms"`
	LibraryVersion int64          `json:"library_version"`
	MatchedAt      int64          `json:"matched_at"`
	ArtistID       string         `json:"artist_id"`
	AlbumID        string         `json:"album_id"`
	CoverArtID     string         `json:"cover_art_id"`
}

type OfflineSet struct {
	DeviceID   string `json:"device_id"`
	PlaylistID string `json:"playlist_id"`
	Enabled    int64  `json:"enabled"`
	UpdatedAt  int64  `json:"updated_at"`
}

type P2pPeer struct {
	PeerID   string         `json:"peer_id"`
	DeviceID sql.NullString `json:"device_id"`
	Name     string         `json:"name"`
	AddedAt  int64          `json:"added_at"`
	LastSeen int64          `json:"last_seen"`
	Addrs    string         `json:"addrs"`
}

type PairingCode struct {
	Code           string         `json:"code"`
	ExpiresAt      int64          `json:"expires_at"`
	UsedAt         sql.NullInt64  `json:"used_at"`
	UsedByDeviceID sql.NullString `json:"used_by_device_id"`
	CreatedAt      int64          `json:"created_at"`
}

type Play struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CatalogID string `json:"catalog_id"`
	PlayedAt  int64  `json:"played_at"`
	MsPlayed  int64  `json:"ms_played"`
	Completed int64  `json:"completed"`
	CreatedAt int64  `json:"created_at"`
}

type ScrobbleLink struct {
	UserID     string `json:"user_id"`
	Provider   string `json:"provider"`
	SessionKey string `json:"session_key"`
	Username   string `json:"username"`
	Status     string `json:"status"`
	CreatedAt  int64  `json:"created_at"`
}

type ScrobbleQueue struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	Provider      string `json:"provider"`
	CatalogID     string `json:"catalog_id"`
	Title         string `json:"title"`
	Artist        string `json:"artist"`
	Album         string `json:"album"`
	DurationMs    int64  `json:"duration_ms"`
	PlayedAt      int64  `json:"played_at"`
	Status        string `json:"status"`
	Attempts      int64  `json:"attempts"`
	NextAttemptAt int64  `json:"next_attempt_at"`
	CreatedAt     int64  `json:"created_at"`
}

type Setting struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

type SyncChange struct {
	Revision   int64  `json:"revision"`
	DeviceID   string `json:"device_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Field      string `json:"field"`
	ValueJson  string `json:"value_json"`
	UpdatedAt  int64  `json:"updated_at"`
	CreatedAt  int64  `json:"created_at"`
	Hlc        int64  `json:"hlc"`
	Seq        int64  `json:"seq"`
	Sig        string `json:"sig"`
}

type SyncCursor struct {
	DeviceID  string `json:"device_id"`
	Revision  int64  `json:"revision"`
	UpdatedAt int64  `json:"updated_at"`
}

type SyncVector struct {
	DeviceID  string `json:"device_id"`
	Seq       int64  `json:"seq"`
	Hlc       int64  `json:"hlc"`
	UpdatedAt int64  `json:"updated_at"`
}

type SyncedPlaylist struct {
	ID              string         `json:"id"`
	Source          string         `json:"source"`
	ExternalID      string         `json:"external_id"`
	Name            string         `json:"name"`
	CoverUrl        string         `json:"cover_url"`
	TracksJson      string         `json:"tracks_json"`
	SyncEnabled     int64          `json:"sync_enabled"`
	SyncIntervalSec int64          `json:"sync_interval_sec"`
	AutoDownload    int64          `json:"auto_download"`
	LastSyncedAt    int64          `json:"last_synced_at"`
	CreatedAt       int64          `json:"created_at"`
	Mode            string         `json:"mode"`
	OwnerUserID     sql.NullString `json:"owner_user_id"`
}

type TrackCrop struct {
	TrackID   string         `json:"track_id"`
	StartMs   int64          `json:"start_ms"`
	EndMs     sql.NullInt64  `json:"end_ms"`
	UpdatedAt int64          `json:"updated_at"`
	CatalogID sql.NullString `json:"catalog_id"`
}

type TrackLoudness struct {
	TrackID   string         `json:"track_id"`
	GainDb    float64        `json:"gain_db"`
	UpdatedAt int64          `json:"updated_at"`
	CatalogID sql.NullString `json:"catalog_id"`
}

type TrackOverride struct {
	TrackID   string         `json:"track_id"`
	Title     string         `json:"title"`
	Artist    string         `json:"artist"`
	UpdatedAt int64          `json:"updated_at"`
	CatalogID sql.NullString `json:"catalog_id"`
}

type TrackQualityOverride struct {
	TrackID   string         `json:"track_id"`
	Quality   string         `json:"quality"`
	UpdatedAt int64          `json:"updated_at"`
	CatalogID sql.NullString `json:"catalog_id"`
}

type User struct {
	ID        string `json:"id"`
	Username  string `json:"username"`
	CreatedAt int64  `json:"created_at"`
}
