// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: not_interested.sql

package db

import (
	"context"
)

const deleteNotInterested = `-- name: DeleteNotInterested :exec
DELETE FROM not_interested WHERE key = ?
`

func (q *Queries) DeleteNotInterested(ctx context.Context, key string) error {
	_, err := q.db.ExecContext(ctx, deleteNotInterested, key)
	return err
}

const listNotInterested = `-- name: ListNotInterested :many
SELECT "key", kind, title, artist, source, external_id, marked_at FROM not_interested ORDER BY marked_at DESC, key
`

func (q *Queries) ListNotInterested(ctx context.Context) ([]NotInterested, error) {
	rows, err := q.db.QueryContext(ctx, listNotInterested)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NotInterested
	for rows.Next() {
		var i NotInterested
		if err := rows.Scan(
			&i.Key,
			&i.Kind,
			&i.Title,
			&i.Artist,
			&i.Source,
			&i.ExternalID,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertNotInterested = `-- name: UpsertNotInterested :exec
INSERT INTO not_interested (key, kind, title, artist, source, external_id, marked_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(key) DO UPDATE SET
  kind = excluded.kind,
  title = excluded.title,
  artist = excluded.artist,
  source = excluded.source,
  external_id = excluded.external_id,
  marked_at = excluded.marked_at
`

type UpsertNotInterestedParams struct {
	Key        string `json:"key"`
	Kind       string `json:"kind"`
	Title      string `json:"title"`
	Artist     string `json:"artist"`
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
	MarkedAt   int64  `json:"marked_at"`
}

func (q *Queries) UpsertNotInterested(ctx context.Context, arg UpsertNotInterestedParams) error {
	_, err := q.db.ExecContext(ctx, upsertNotInterested,
		arg.Key,
		arg.Kind,
		arg.Title,
		arg.Artist,
		arg.Source,
		arg.ExternalID,
		arg.MarkedAt,
	)
	return err
}
