// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: offline_set.sql

package db

import (
	"context"
)

const deleteOfflineFile = `-- name: DeleteOfflineFile :exec
DELETE FROM offline_file WHERE rel_path = ?
`

func (q *Queries) DeleteOfflineFile(ctx context.Context, relPath string) error {
	_, err := q.db.ExecContext(ctx, deleteOfflineFile, relPath)
	return err
}

const deleteOfflineSetEntry = `-- name: DeleteOfflineSetEntry :exec
DELETE FROM offline_set WHERE device_id = ? AND playlist_id = ?
`

type DeleteOfflineSetEntryParams struct {
	DeviceID   string `json:"device_id"`
	PlaylistID string `json:"playlist_id"`
}

func (q *Queries) DeleteOfflineSetEntry(ctx context.Context, arg DeleteOfflineSetEntryParams) error {
	_, err := q.db.ExecContext(ctx, deleteOfflineSetEntry, arg.DeviceID, arg.PlaylistID)
	return err
}

const deleteOfflineSetForPlaylist = `-- name: DeleteOfflineSetForPlaylist :exec
DELETE FROM offline_set WHERE playlist_id = ?
`

func (q *Queries) DeleteOfflineSetForPlaylist(ctx context.Context, playlistID string) error {
	_, err := q.db.ExecContext(ctx, deleteOfflineSetForPlaylist, playlistID)
	return err
}

const getOfflineSetEntry = `-- name: GetOfflineSetEntry :one
SELECT device_id, playlist_id, enabled, updated_at FROM offline_set WHERE device_id = ? AND playlist_id = ?
`

type GetOfflineSetEntryParams struct {
	DeviceID   string `json:"device_id"`
	PlaylistID string `json:"playlist_id"`
}

func (q *Queries) GetOfflineSetEntry(ctx context.Context, arg GetOfflineSetEntryParams) (OfflineSet, error) {
	row := q.db.QueryRowContext(ctx, getOfflineSetEntry, arg.DeviceID, arg.PlaylistID)
	var i OfflineSet
	err := row.Scan(
		&i.DeviceID,
		&i.PlaylistID,
		&i.Enabled,
		&i.UpdatedAt,
	)
	return i, err
}

const listOfflineFiles = `-- name: ListOfflineFiles :many
SELECT rel_path, content_hash, fetched_at FROM offline_file ORDER BY rel_path
`

func (q *Queries) ListOfflineFiles(ctx context.Context) ([]OfflineFile, error) {
	rows, err := q.db.QueryContext(ctx, listOfflineFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfflineFile
	for rows.Next() {
		var i OfflineFile
		if err := rows.Scan(&i.RelPath, &i.ContentHash, &i.FetchedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOfflineSetForDevice = `-- name: ListOfflineSetForDevice :many
SELECT device_id, playlist_id, enabled, updated_at FROM offline_set WHERE device_id = ? ORDER BY playlist_id
`

func (q *Queries) ListOfflineSetForDevice(ctx context.Context, deviceID string) ([]OfflineSet, error) {
	rows, err := q.db.QueryContext(ctx, listOfflineSetForDevice, deviceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OfflineSet
	for rows.Next() {
		var i OfflineSet
		if err := rows.Scan(
			&i.DeviceID,
			&i.PlaylistID,
			&i.Enabled,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertOfflineFile = `-- name: UpsertOfflineFile :exec
INSERT INTO offline_file (rel_path, content_hash, fetched_at) VALUES (?, ?, ?) ON CONFLICT(rel_path) DO UPDATE SET content_hash = excluded.content_hash, fetched_at = excluded.fetched_at
`

type UpsertOfflineFileParams struct {
	RelPath     string `json:"rel_path"`
	ContentHash string `json:"content_hash"`
	FetchedAt   int64  `json:"fetched_at"`
}

func (q *Queries) UpsertOfflineFile(ctx context.Context, arg UpsertOfflineFileParams) error {
	_, err := q.db.ExecContext(ctx, upsertOfflineFile, arg.RelPath, arg.ContentHash, arg.FetchedAt)
	return err
}

const upsertOfflineSet = `-- name: UpsertOfflineSet :exec
INSERT INTO offline_set (device_id, playlist_id, enabled, updated_at) VALUES (?, ?, ?, ?) ON CONFLICT(device_id, playlist_id) DO UPDATE SET enabled = excluded.enabled, updated_at = excluded.updated_at
`

type UpsertOfflineSetParams struct {
	DeviceID   string `json:"device_id"`
	PlaylistID string `json:"playlist_id"`
	Enabled    int64  `json:"enabled"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) UpsertOfflineSet(ctx context.Context, arg UpsertOfflineSetParams) error {
	_, err := q.db.ExecContext(ctx, upsertOfflineSet,
		arg.DeviceID,
		arg.PlaylistID,
		arg.Enabled,
		arg.UpdatedAt,
	)
	return err
}
