// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: p2p_peer.sql

package db

import (
	"context"
	"database/sql"
)

const deleteTrustedPeer = `-- name: DeleteTrustedPeer :exec
DELETE FROM p2p_peer WHERE peer_id = ?
`

func (q *Queries) DeleteTrustedPeer(ctx context.Context, peerID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrustedPeer, peerID)
	return err
}

const deleteTrustedPeersByDevice = `-- name: DeleteTrustedPeersByDevice :exec
DELETE FROM p2p_peer WHERE device_id = ?
`

func (q *Queries) DeleteTrustedPeersByDevice(ctx context.Context, deviceID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteTrustedPeersByDevice, deviceID)
	return err
}

const getTrustedPeer = `-- name: GetTrustedPeer :one
SELECT peer_id, device_id, name, added_at, last_seen, addrs FROM p2p_peer WHERE peer_id = ?
`

func (q *Queries) GetTrustedPeer(ctx context.Context, peerID string) (P2pPeer, error) {
	row := q.db.QueryRowContext(ctx, getTrustedPeer, peerID)
	var i P2pPeer
	err := row.Scan(
		&i.PeerID,
		&i.DeviceID,
		&i.Name,
		&i.AddedAt,
		&i.LastSeen,
		&i.Addrs,
	)
	return i, err
}

const listTrustedPeers = `-- name: ListTrustedPeers :many
SELECT peer_id, device_id, name, added_at, last_seen, addrs FROM p2p_peer ORDER BY added_at
`

func (q *Queries) ListTrustedPeers(ctx context.Context) ([]P2pPeer, error) {
	rows, err := q.db.QueryContext(ctx, listTrustedPeers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []P2pPeer
	for rows.Next() {
		var i P2pPeer
		if err := rows.Scan(
			&i.PeerID,
			&i.DeviceID,
			&i.Name,
			&i.AddedAt,
			&i.LastSeen,
			&i.Addrs,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTrustedPeerAddrs = `-- name: SetTrustedPeerAddrs :exec
UPDATE p2p_peer SET addrs = ? WHERE peer_id = ?
`

type SetTrustedPeerAddrsParams struct {
	Addrs  string `json:"addrs"`
	PeerID string `json:"peer_id"`
}

func (q *Queries) SetTrustedPeerAddrs(ctx context.Context, arg SetTrustedPeerAddrsParams) error {
	_, err := q.db.ExecContext(ctx, setTrustedPeerAddrs, arg.Addrs, arg.PeerID)
	return err
}

const touchTrustedPeer = `-- name: TouchTrustedPeer :exec
UPDATE p2p_peer SET last_seen = unixepoch() WHERE peer_id = ?
`

func (q *Queries) TouchTrustedPeer(ctx context.Context, peerID string) error {
	_, err := q.db.ExecContext(ctx, touchTrustedPeer, peerID)
	return err
}

const trustPeer = `-- name: TrustPeer :exec
INSERT INTO p2p_peer (peer_id, device_id, name, added_at, last_seen) VALUES (?, ?, ?, unixepoch(), unixepoch())
ON CONFLICT(peer_id) DO UPDATE SET device_id = excluded.device_id, name = excluded.name, last_seen = unixepoch()
`

type TrustPeerParams struct {
	PeerID   string         `json:"peer_id"`
	DeviceID sql.NullString `json:"device_id"`
	Name     string         `json:"name"`
}

// addrs is deliberately not touched on conflict: re-pairing an existing peer
// must not discard the addresses that are how we reach it.
func (q *Queries) TrustPeer(ctx context.Context, arg TrustPeerParams) error {
	_, err := q.db.ExecContext(ctx, trustPeer, arg.PeerID, arg.DeviceID, arg.Name)
	return err
}
