// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: pairing.sql

package db

import (
	"context"
	"database/sql"
)

const createPairingCode = `-- name: CreatePairingCode :exec
INSERT INTO pairing_code (code, expires_at, created_at) VALUES (?, ?, unixepoch())
`

type CreatePairingCodeParams struct {
	Code      string `json:"code"`
	ExpiresAt int64  `json:"expires_at"`
}

func (q *Queries) CreatePairingCode(ctx context.Context, arg CreatePairingCodeParams) error {
	_, err := q.db.ExecContext(ctx, createPairingCode, arg.Code, arg.ExpiresAt)
	return err
}

const deleteExpiredPairingCodes = `-- name: DeleteExpiredPairingCodes :exec
DELETE FROM pairing_code WHERE expires_at < unixepoch() AND used_at IS NULL
`

func (q *Queries) DeleteExpiredPairingCodes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredPairingCodes)
	return err
}

const getPairingCode = `-- name: GetPairingCode :one
SELECT code, expires_at, used_at, used_by_device_id, created_at FROM pairing_code WHERE code = ?
`

func (q *Queries) GetPairingCode(ctx context.Context, code string) (PairingCode, error) {
	row := q.db.QueryRowContext(ctx, getPairingCode, code)
	var i PairingCode
	err := row.Scan(
		&i.Code,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.UsedByDeviceID,
		&i.CreatedAt,
	)
	return i, err
}

const listPairingCodes = `-- name: ListPairingCodes :many
SELECT code, expires_at, used_at, used_by_device_id, created_at FROM pairing_code ORDER BY created_at DESC
`

func (q *Queries) ListPairingCodes(ctx context.Context) ([]PairingCode, error) {
	rows, err := q.db.QueryContext(ctx, listPairingCodes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PairingCode
	for rows.Next() {
		var i PairingCode
		if err := rows.Scan(
			&i.Code,
			&i.ExpiresAt,
			&i.UsedAt,
			&i.UsedByDeviceID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markPairingCodeUsed = `-- name: MarkPairingCodeUsed :exec
UPDATE pairing_code SET used_at = unixepoch(), used_by_device_id = ? WHERE code = ?
`

type MarkPairingCodeUsedParams struct {
	UsedByDeviceID sql.NullString `json:"used_by_device_id"`
	Code           string         `json:"code"`
}

func (q *Queries) MarkPairingCodeUsed(ctx context.Context, arg MarkPairingCodeUsedParams) error {
	_, err := q.db.ExecContext(ctx, markPairingCodeUsed, arg.UsedByDeviceID, arg.Code)
	return err
}
