// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plays.sql

package db

import (
	"context"
	"database/sql"
)

const countPlays = `-- name: CountPlays :one
SELECT COUNT(*) FROM plays WHERE qualified = 1
`

func (q *Queries) CountPlays(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlays)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlaysByCatalog = `-- name: CountPlaysByCatalog :one
SELECT COUNT(*) FROM plays WHERE user_id = ? AND catalog_id = ? AND qualified = 1
`

type CountPlaysByCatalogParams struct {
	UserID    string `json:"user_id"`
	CatalogID string `json:"catalog_id"`
}

func (q *Queries) CountPlaysByCatalog(ctx context.Context, arg CountPlaysByCatalogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaysByCatalog, arg.UserID, arg.CatalogID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlay = `-- name: DeletePlay :exec
DELETE FROM plays WHERE id = ? AND user_id = ?
`

type DeletePlayParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePlay(ctx context.Context, arg DeletePlayParams) error {
	_, err := q.db.ExecContext(ctx, deletePlay, arg.ID, arg.UserID)
	return err
}

const deleteReplicatedPlay = `-- name: DeleteReplicatedPlay :exec
DELETE FROM plays WHERE id = ?
`

func (q *Queries) DeleteReplicatedPlay(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteReplicatedPlay, id)
	return err
}

const distinctDurableCanonicalIDs = `-- name: DistinctDurableCanonicalIDs :many
SELECT DISTINCT catalog_id FROM plays WHERE catalog_id != ''
UNION
SELECT DISTINCT canonical_id FROM download_jobs WHERE canonical_id != ''
LIMIT ?
`

func (q *Queries) DistinctDurableCanonicalIDs(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, distinctDurableCanonicalIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var catalog_id string
		if err := rows.Scan(&catalog_id); err != nil {
			return nil, err
		}
		items = append(items, catalog_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlay = `-- name: GetPlay :one
SELECT id, user_id, catalog_id, played_at, ms_played, completed, created_at, origin, session_id, qualified FROM plays WHERE id = ?
`

func (q *Queries) GetPlay(ctx context.Context, id string) (Play, error) {
	row := q.db.QueryRowContext(ctx, getPlay, id)
	var i Play
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CatalogID,
		&i.PlayedAt,
		&i.MsPlayed,
		&i.Completed,
		&i.CreatedAt,
		&i.Origin,
		&i.SessionID,
		&i.Qualified,
	)
	return i, err
}

const insertPlay = `-- name: InsertPlay :exec
INSERT INTO plays (id, user_id, catalog_id, played_at, ms_played, completed, created_at, origin, session_id, qualified)
VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertPlayParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CatalogID string `json:"catalog_id"`
	PlayedAt  int64  `json:"played_at"`
	MsPlayed  int64  `json:"ms_played"`
	Completed int64  `json:"completed"`
	CreatedAt int64  `json:"created_at"`
	Origin    string `json:"origin"`
	SessionID string `json:"session_id"`
	Qualified int64  `json:"qualified"`
}

func (q *Queries) InsertPlay(ctx context.Context, arg InsertPlayParams) error {
	_, err := q.db.ExecContext(ctx, insertPlay,
		arg.ID,
		arg.UserID,
		arg.CatalogID,
		arg.PlayedAt,
		arg.MsPlayed,
		arg.Completed,
		arg.CreatedAt,
		arg.Origin,
		arg.SessionID,
		arg.Qualified,
	)
	return err
}

const insertPlayIfAbsent = `-- name: InsertPlayIfAbsent :exec
INSERT OR IGNORE INTO plays (id, user_id, catalog_id, played_at, ms_played, completed, created_at, origin, session_id, qualified)
VALUES (?,?,?,?,?,?,?,?,?,?)
`

type InsertPlayIfAbsentParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CatalogID string `json:"catalog_id"`
	PlayedAt  int64  `json:"played_at"`
	MsPlayed  int64  `json:"ms_played"`
	Completed int64  `json:"completed"`
	CreatedAt int64  `json:"created_at"`
	Origin    string `json:"origin"`
	SessionID string `json:"session_id"`
	Qualified int64  `json:"qualified"`
}

func (q *Queries) InsertPlayIfAbsent(ctx context.Context, arg InsertPlayIfAbsentParams) error {
	_, err := q.db.ExecContext(ctx, insertPlayIfAbsent,
		arg.ID,
		arg.UserID,
		arg.CatalogID,
		arg.PlayedAt,
		arg.MsPlayed,
		arg.Completed,
		arg.CreatedAt,
		arg.Origin,
		arg.SessionID,
		arg.Qualified,
	)
	return err
}

const insertRecommendationAddIfAbsent = `-- name: InsertRecommendationAddIfAbsent :exec
INSERT OR IGNORE INTO recommendation_add (id, user_id, origin, action, created_at)
VALUES (?, ?, ?, ?, ?)
`

type InsertRecommendationAddIfAbsentParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	Origin    string `json:"origin"`
	Action    string `json:"action"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertRecommendationAddIfAbsent(ctx context.Context, arg InsertRecommendationAddIfAbsentParams) error {
	_, err := q.db.ExecContext(ctx, insertRecommendationAddIfAbsent,
		arg.ID,
		arg.UserID,
		arg.Origin,
		arg.Action,
		arg.CreatedAt,
	)
	return err
}

const libraryArtistTrackCounts = `-- name: LibraryArtistTrackCounts :many
SELECT CAST(MIN(e.artist) AS TEXT) AS artist, COUNT(DISTINCT e.id) AS tracks
FROM catalog_entity e
JOIN backend_binding b ON b.catalog_id = e.id AND b.backend_id != '' AND b.known_absent = 0
WHERE e.kind = 'track' AND e.artist != ''
GROUP BY lower(e.artist)
ORDER BY tracks DESC, lower(MIN(e.artist))
LIMIT ?1
`

type LibraryArtistTrackCountsRow struct {
	Artist string `json:"artist"`
	Tracks int64  `json:"tracks"`
}

func (q *Queries) LibraryArtistTrackCounts(ctx context.Context, resultLimit int64) ([]LibraryArtistTrackCountsRow, error) {
	rows, err := q.db.QueryContext(ctx, libraryArtistTrackCounts, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryArtistTrackCountsRow
	for rows.Next() {
		var i LibraryArtistTrackCountsRow
		if err := rows.Scan(&i.Artist, &i.Tracks); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const libraryTracksByArtist = `-- name: LibraryTracksByArtist :many
SELECT e.id, e.title, e.artist, e.album, e.duration_ms, e.isrc, e.mbid,
       CAST(MIN(b.backend_id) AS TEXT) AS backend_id, CAST(MIN(b.cover_art_id) AS TEXT) AS cover_art_id
FROM catalog_entity e
JOIN backend_binding b ON b.catalog_id = e.id AND b.backend_id != '' AND b.known_absent = 0
WHERE e.kind = 'track' AND lower(e.artist) = lower(?1)
GROUP BY e.id
ORDER BY lower(e.album), lower(e.title), e.id
LIMIT ?2
`

type LibraryTracksByArtistParams struct {
	Artist      string `json:"artist"`
	ResultLimit int64  `json:"result_limit"`
}

type LibraryTracksByArtistRow struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Artist     string `json:"artist"`
	Album      string `json:"album"`
	DurationMs int64  `json:"duration_ms"`
	Isrc       string `json:"isrc"`
	Mbid       string `json:"mbid"`
	BackendID  string `json:"backend_id"`
	CoverArtID string `json:"cover_art_id"`
}

func (q *Queries) LibraryTracksByArtist(ctx context.Context, arg LibraryTracksByArtistParams) ([]LibraryTracksByArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, libraryTracksByArtist, arg.Artist, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LibraryTracksByArtistRow
	for rows.Next() {
		var i LibraryTracksByArtistRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationMs,
			&i.Isrc,
			&i.Mbid,
			&i.BackendID,
			&i.CoverArtID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllPlays = `-- name: ListAllPlays :many
SELECT id, user_id, catalog_id, played_at, ms_played, completed, created_at, origin, session_id, qualified FROM plays ORDER BY played_at ASC
`

func (q *Queries) ListAllPlays(ctx context.Context) ([]Play, error) {
	rows, err := q.db.QueryContext(ctx, listAllPlays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Play
	for rows.Next() {
		var i Play
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CatalogID,
			&i.PlayedAt,
			&i.MsPlayed,
			&i.Completed,
			&i.CreatedAt,
			&i.Origin,
			&i.SessionID,
			&i.Qualified,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllRecommendationAdds = `-- name: ListAllRecommendationAdds :many
SELECT id, user_id, origin, "action", created_at FROM recommendation_add ORDER BY created_at, id
`

func (q *Queries) ListAllRecommendationAdds(ctx context.Context) ([]RecommendationAdd, error) {
	rows, err := q.db.QueryContext(ctx, listAllRecommendationAdds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationAdd
	for rows.Next() {
		var i RecommendationAdd
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Origin,
			&i.Action,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedPlays = `-- name: ListDeletedPlays :many
SELECT DISTINCT p.id FROM plays p JOIN sync_change s ON s.entity_id = p.id
WHERE s.entity_type = 'play' AND s.field = '__deleted'
`

func (q *Queries) ListDeletedPlays(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listDeletedPlays)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlayedSince = `-- name: ListPlayedSince :many
SELECT DISTINCT e.title, e.artist
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.played_at >= ? AND p.qualified = 1
`

type ListPlayedSinceRow struct {
	Title  string `json:"title"`
	Artist string `json:"artist"`
}

func (q *Queries) ListPlayedSince(ctx context.Context, playedAt int64) ([]ListPlayedSinceRow, error) {
	rows, err := q.db.QueryContext(ctx, listPlayedSince, playedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlayedSinceRow
	for rows.Next() {
		var i ListPlayedSinceRow
		if err := rows.Scan(&i.Title, &i.Artist); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentPlays = `-- name: ListRecentPlays :many
SELECT p.id, p.catalog_id, p.played_at, e.title, e.artist, e.album
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.played_at < ?
  AND p.qualified = 1
ORDER BY p.played_at DESC LIMIT ?
`

type ListRecentPlaysParams struct {
	UserID   string `json:"user_id"`
	PlayedAt int64  `json:"played_at"`
	Limit    int64  `json:"limit"`
}

type ListRecentPlaysRow struct {
	ID        string `json:"id"`
	CatalogID string `json:"catalog_id"`
	PlayedAt  int64  `json:"played_at"`
	Title     string `json:"title"`
	Artist    string `json:"artist"`
	Album     string `json:"album"`
}

func (q *Queries) ListRecentPlays(ctx context.Context, arg ListRecentPlaysParams) ([]ListRecentPlaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPlays, arg.UserID, arg.PlayedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPlaysRow
	for rows.Next() {
		var i ListRecentPlaysRow
		if err := rows.Scan(
			&i.ID,
			&i.CatalogID,
			&i.PlayedAt,
			&i.Title,
			&i.Artist,
			&i.Album,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const localRecommendationArtists = `-- name: LocalRecommendationArtists :many
WITH candidate_artists AS (
  SELECT e.artist,
         4 * EXISTS (
           SELECT 1 FROM synced_playlists sp
           WHERE EXISTS (SELECT 1 FROM json_each(sp.tracks_json) jt
                         WHERE lower(json_extract(jt.value, '$.artist')) = lower(?2))
             AND EXISTS (SELECT 1 FROM json_each(sp.tracks_json) jt
                         WHERE lower(json_extract(jt.value, '$.artist')) = lower(e.artist))
         ) +
         4 * EXISTS (
           SELECT 1
           FROM plays ps
           JOIN catalog_entity se ON se.id = ps.catalog_id
           JOIN plays pc ON pc.session_id = ps.session_id AND pc.session_id != ''
           JOIN catalog_entity ce ON ce.id = pc.catalog_id
           WHERE lower(se.artist) = lower(?2) AND lower(ce.artist) = lower(e.artist)
         ) AS score
  FROM catalog_entity e
  JOIN backend_binding b ON b.catalog_id = e.id AND b.backend_id != '' AND b.known_absent = 0
  WHERE e.kind = 'track' AND lower(e.artist) != lower(?2)
  GROUP BY e.artist
)
SELECT artist, score FROM candidate_artists WHERE score > 0
ORDER BY score DESC, lower(artist) LIMIT ?1
`

type LocalRecommendationArtistsParams struct {
	ResultLimit int64  `json:"result_limit"`
	SeedArtist  string `json:"seed_artist"`
}

type LocalRecommendationArtistsRow struct {
	Artist string `json:"artist"`
	Score  int64  `json:"score"`
}

func (q *Queries) LocalRecommendationArtists(ctx context.Context, arg LocalRecommendationArtistsParams) ([]LocalRecommendationArtistsRow, error) {
	rows, err := q.db.QueryContext(ctx, localRecommendationArtists, arg.ResultLimit, arg.SeedArtist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalRecommendationArtistsRow
	for rows.Next() {
		var i LocalRecommendationArtistsRow
		if err := rows.Scan(&i.Artist, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const localRecommendationTracks = `-- name: LocalRecommendationTracks :many
WITH seed AS (
  SELECT id, artist, album
  FROM catalog_entity
  WHERE kind = 'track' AND lower(trim(artist)) = lower(trim(?2))
    AND (CAST(?3 AS TEXT) = '' OR lower(trim(title)) = lower(trim(CAST(?3 AS TEXT))))
  LIMIT 1
), candidates AS (
  SELECT e.id, e.title, e.artist, e.album, e.duration_ms, e.isrc, e.mbid,
         b.backend_id, b.cover_art_id,
         CASE WHEN lower(e.artist) = lower(seed.artist) THEN 3 ELSE 0 END +
         CASE WHEN seed.album != '' AND lower(e.album) = lower(seed.album) THEN 2 ELSE 0 END +
         4 * EXISTS (
           SELECT 1 FROM synced_playlists sp
           WHERE EXISTS (SELECT 1 FROM json_each(sp.tracks_json) jt
                         WHERE lower(json_extract(jt.value, '$.artist')) = lower(seed.artist)
                           AND (CAST(?3 AS TEXT) = '' OR lower(json_extract(jt.value, '$.title')) = lower(CAST(?3 AS TEXT))))
             AND EXISTS (SELECT 1 FROM json_each(sp.tracks_json) jt
                         WHERE lower(json_extract(jt.value, '$.artist')) = lower(e.artist)
                           AND lower(json_extract(jt.value, '$.title')) = lower(e.title))
         ) +
         4 * EXISTS (
           SELECT 1 FROM plays ps JOIN plays pc ON pc.session_id = ps.session_id
           WHERE ps.catalog_id = seed.id AND pc.catalog_id = e.id AND ps.session_id != ''
         ) AS score
  FROM catalog_entity e
  JOIN backend_binding b ON b.catalog_id = e.id AND b.backend_id != '' AND b.known_absent = 0
  JOIN seed
  WHERE e.kind = 'track' AND (CAST(?3 AS TEXT) = '' OR e.id != seed.id)
)
SELECT id, title, artist, album, duration_ms, isrc, mbid, backend_id, cover_art_id, score FROM candidates WHERE score > 0
GROUP BY id ORDER BY score DESC, lower(artist), lower(title) LIMIT ?1
`

type LocalRecommendationTracksParams struct {
	ResultLimit int64  `json:"result_limit"`
	SeedArtist  string `json:"seed_artist"`
	SeedTitle   string `json:"seed_title"`
}

type LocalRecommendationTracksRow struct {
	ID         string `json:"id"`
	Title      string `json:"title"`
	Artist     string `json:"artist"`
	Album      string `json:"album"`
	DurationMs int64  `json:"duration_ms"`
	Isrc       string `json:"isrc"`
	Mbid       string `json:"mbid"`
	BackendID  string `json:"backend_id"`
	CoverArtID string `json:"cover_art_id"`
	Score      int64  `json:"score"`
}

func (q *Queries) LocalRecommendationTracks(ctx context.Context, arg LocalRecommendationTracksParams) ([]LocalRecommendationTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, localRecommendationTracks, arg.ResultLimit, arg.SeedArtist, arg.SeedTitle)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LocalRecommendationTracksRow
	for rows.Next() {
		var i LocalRecommendationTracksRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationMs,
			&i.Isrc,
			&i.Mbid,
			&i.BackendID,
			&i.CoverArtID,
			&i.Score,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recommendationStats = `-- name: RecommendationStats :many
WITH origins AS (
  SELECT p.origin FROM plays p
  WHERE p.user_id = ?1 AND p.origin != '' AND p.played_at >= ?2 AND p.played_at < ?3
  UNION
  SELECT a.origin FROM recommendation_add a
  WHERE a.user_id = ?1 AND a.created_at >= ?2 AND a.created_at < ?3
), play_totals AS (
  SELECT p.origin, COUNT(*) AS plays,
         SUM(CASE WHEN p.qualified = 0 THEN 1 ELSE 0 END) AS skips,
         SUM(CASE WHEN p.completed = 1 THEN 1 ELSE 0 END) AS completions
  FROM plays p
  WHERE p.user_id = ?1 AND p.origin != '' AND p.played_at >= ?2 AND p.played_at < ?3
  GROUP BY p.origin
), add_totals AS (
  SELECT a.origin, COUNT(*) AS additions
  FROM recommendation_add a
  WHERE a.user_id = ?1 AND a.created_at >= ?2 AND a.created_at < ?3
  GROUP BY a.origin
)
SELECT origins.origin,
       COALESCE(play_totals.plays, 0) AS plays,
       COALESCE(play_totals.skips, 0) AS skips,
       COALESCE(play_totals.completions, 0) AS completions,
       COALESCE(add_totals.additions, 0) AS additions
FROM origins
LEFT JOIN play_totals USING (origin)
LEFT JOIN add_totals USING (origin)
ORDER BY origins.origin
`

type RecommendationStatsParams struct {
	UserID   string `json:"user_id"`
	FromTime int64  `json:"from_time"`
	ToTime   int64  `json:"to_time"`
}

type RecommendationStatsRow struct {
	Origin      string  `json:"origin"`
	Plays       int64   `json:"plays"`
	Skips       float64 `json:"skips"`
	Completions float64 `json:"completions"`
	Additions   int64   `json:"additions"`
}

func (q *Queries) RecommendationStats(ctx context.Context, arg RecommendationStatsParams) ([]RecommendationStatsRow, error) {
	rows, err := q.db.QueryContext(ctx, recommendationStats, arg.UserID, arg.FromTime, arg.ToTime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecommendationStatsRow
	for rows.Next() {
		var i RecommendationStatsRow
		if err := rows.Scan(
			&i.Origin,
			&i.Plays,
			&i.Skips,
			&i.Completions,
			&i.Additions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointPlays = `-- name: RepointPlays :exec
UPDATE plays SET catalog_id = ? WHERE catalog_id = ?
`

type RepointPlaysParams struct {
	CatalogID   string `json:"catalog_id"`
	CatalogID_2 string `json:"catalog_id_2"`
}

func (q *Queries) RepointPlays(ctx context.Context, arg RepointPlaysParams) error {
	_, err := q.db.ExecContext(ctx, repointPlays, arg.CatalogID, arg.CatalogID_2)
	return err
}

const statsEntityAlbum = `-- name: StatsEntityAlbum :one
SELECT
    COUNT(*)         AS plays,
    COALESCE(SUM(p.ms_played), 0) AS ms_played,
    MIN(p.played_at) AS first_played,
    MAX(p.played_at) AS last_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND e.album = ? AND e.artist = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
`

type StatsEntityAlbumParams struct {
	UserID     string `json:"user_id"`
	Album      string `json:"album"`
	Artist     string `json:"artist"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsEntityAlbumRow struct {
	Plays       int64       `json:"plays"`
	MsPlayed    interface{} `json:"ms_played"`
	FirstPlayed interface{} `json:"first_played"`
	LastPlayed  interface{} `json:"last_played"`
}

func (q *Queries) StatsEntityAlbum(ctx context.Context, arg StatsEntityAlbumParams) (StatsEntityAlbumRow, error) {
	row := q.db.QueryRowContext(ctx, statsEntityAlbum,
		arg.UserID,
		arg.Album,
		arg.Artist,
		arg.PlayedAt,
		arg.PlayedAt_2,
	)
	var i StatsEntityAlbumRow
	err := row.Scan(
		&i.Plays,
		&i.MsPlayed,
		&i.FirstPlayed,
		&i.LastPlayed,
	)
	return i, err
}

const statsEntityArtist = `-- name: StatsEntityArtist :one
SELECT
    COUNT(*)         AS plays,
    COALESCE(SUM(p.ms_played), 0) AS ms_played,
    MIN(p.played_at) AS first_played,
    MAX(p.played_at) AS last_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND e.artist = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
`

type StatsEntityArtistParams struct {
	UserID     string `json:"user_id"`
	Artist     string `json:"artist"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsEntityArtistRow struct {
	Plays       int64       `json:"plays"`
	MsPlayed    interface{} `json:"ms_played"`
	FirstPlayed interface{} `json:"first_played"`
	LastPlayed  interface{} `json:"last_played"`
}

func (q *Queries) StatsEntityArtist(ctx context.Context, arg StatsEntityArtistParams) (StatsEntityArtistRow, error) {
	row := q.db.QueryRowContext(ctx, statsEntityArtist,
		arg.UserID,
		arg.Artist,
		arg.PlayedAt,
		arg.PlayedAt_2,
	)
	var i StatsEntityArtistRow
	err := row.Scan(
		&i.Plays,
		&i.MsPlayed,
		&i.FirstPlayed,
		&i.LastPlayed,
	)
	return i, err
}

const statsEntityTrack = `-- name: StatsEntityTrack :one
SELECT
    COUNT(*)         AS plays,
    COALESCE(SUM(p.ms_played), 0) AS ms_played,
    MIN(p.played_at) AS first_played,
    MAX(p.played_at) AS last_played
FROM plays p
WHERE p.user_id = ? AND p.catalog_id = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
`

type StatsEntityTrackParams struct {
	UserID     string `json:"user_id"`
	CatalogID  string `json:"catalog_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsEntityTrackRow struct {
	Plays       int64       `json:"plays"`
	MsPlayed    interface{} `json:"ms_played"`
	FirstPlayed interface{} `json:"first_played"`
	LastPlayed  interface{} `json:"last_played"`
}

func (q *Queries) StatsEntityTrack(ctx context.Context, arg StatsEntityTrackParams) (StatsEntityTrackRow, error) {
	row := q.db.QueryRowContext(ctx, statsEntityTrack,
		arg.UserID,
		arg.CatalogID,
		arg.PlayedAt,
		arg.PlayedAt_2,
	)
	var i StatsEntityTrackRow
	err := row.Scan(
		&i.Plays,
		&i.MsPlayed,
		&i.FirstPlayed,
		&i.LastPlayed,
	)
	return i, err
}

const statsPlaysInWindow = `-- name: StatsPlaysInWindow :many
SELECT p.played_at, p.ms_played
FROM plays p
WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
ORDER BY p.played_at ASC
`

type StatsPlaysInWindowParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsPlaysInWindowRow struct {
	PlayedAt int64 `json:"played_at"`
	MsPlayed int64 `json:"ms_played"`
}

func (q *Queries) StatsPlaysInWindow(ctx context.Context, arg StatsPlaysInWindowParams) ([]StatsPlaysInWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, statsPlaysInWindow, arg.UserID, arg.PlayedAt, arg.PlayedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsPlaysInWindowRow
	for rows.Next() {
		var i StatsPlaysInWindowRow
		if err := rows.Scan(&i.PlayedAt, &i.MsPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsSummary = `-- name: StatsSummary :one
SELECT
    COUNT(*)                    AS plays,
    COUNT(DISTINCT p.catalog_id) AS distinct_tracks,
    COUNT(DISTINCT e.artist)    AS distinct_artists,
    COUNT(DISTINCT e.album)     AS distinct_albums,
    COALESCE(SUM(p.ms_played), 0) AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
`

type StatsSummaryParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsSummaryRow struct {
	Plays           int64       `json:"plays"`
	DistinctTracks  int64       `json:"distinct_tracks"`
	DistinctArtists int64       `json:"distinct_artists"`
	DistinctAlbums  int64       `json:"distinct_albums"`
	MsPlayed        interface{} `json:"ms_played"`
}

func (q *Queries) StatsSummary(ctx context.Context, arg StatsSummaryParams) (StatsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, statsSummary, arg.UserID, arg.PlayedAt, arg.PlayedAt_2)
	var i StatsSummaryRow
	err := row.Scan(
		&i.Plays,
		&i.DistinctTracks,
		&i.DistinctArtists,
		&i.DistinctAlbums,
		&i.MsPlayed,
	)
	return i, err
}

const statsTopAlbums = `-- name: StatsTopAlbums :many
WITH aggregated AS (
    SELECT
        MIN(p.catalog_id) AS catalog_id,
        e.album,
        e.artist,
        COUNT(*)         AS plays,
        SUM(p.ms_played) AS ms_played
    FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
    WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
    GROUP BY e.album, e.artist
)
SELECT
    CAST(a.catalog_id AS TEXT) AS catalog_id,
    e.title,
    a.album,
    a.artist,
    CAST(e.source AS TEXT) AS source,
    CAST(e.external_id AS TEXT) AS external_id,
    a.plays,
    a.ms_played
FROM aggregated a JOIN catalog_entity e ON e.id = a.catalog_id
ORDER BY a.plays DESC, a.ms_played DESC
LIMIT ?
`

type StatsTopAlbumsParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopAlbumsRow struct {
	CatalogID  string          `json:"catalog_id"`
	Title      string          `json:"title"`
	Album      string          `json:"album"`
	Artist     string          `json:"artist"`
	Source     string          `json:"source"`
	ExternalID string          `json:"external_id"`
	Plays      int64           `json:"plays"`
	MsPlayed   sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopAlbums(ctx context.Context, arg StatsTopAlbumsParams) ([]StatsTopAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopAlbums,
		arg.UserID,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopAlbumsRow
	for rows.Next() {
		var i StatsTopAlbumsRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Album,
			&i.Artist,
			&i.Source,
			&i.ExternalID,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopArtists = `-- name: StatsTopArtists :many
WITH aggregated AS (
    SELECT
        MIN(p.catalog_id) AS catalog_id,
        e.artist,
        COUNT(*)         AS plays,
        SUM(p.ms_played) AS ms_played
    FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
    WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
    GROUP BY e.artist
)
SELECT
    CAST(a.catalog_id AS TEXT) AS catalog_id,
    e.title,
    a.artist,
    e.album,
    CAST(e.source AS TEXT) AS source,
    CAST(e.external_id AS TEXT) AS external_id,
    a.plays,
    a.ms_played
FROM aggregated a JOIN catalog_entity e ON e.id = a.catalog_id
ORDER BY a.plays DESC, a.ms_played DESC
LIMIT ?
`

type StatsTopArtistsParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopArtistsRow struct {
	CatalogID  string          `json:"catalog_id"`
	Title      string          `json:"title"`
	Artist     string          `json:"artist"`
	Album      string          `json:"album"`
	Source     string          `json:"source"`
	ExternalID string          `json:"external_id"`
	Plays      int64           `json:"plays"`
	MsPlayed   sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopArtists(ctx context.Context, arg StatsTopArtistsParams) ([]StatsTopArtistsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopArtists,
		arg.UserID,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopArtistsRow
	for rows.Next() {
		var i StatsTopArtistsRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Source,
			&i.ExternalID,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopTracks = `-- name: StatsTopTracks :many
SELECT
    p.catalog_id,
    e.title,
    e.artist,
    e.album,
    e.source,
    e.external_id,
    COUNT(*)          AS plays,
    SUM(p.ms_played)  AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
GROUP BY p.catalog_id
ORDER BY COUNT(*) DESC, SUM(p.ms_played) DESC
LIMIT ?
`

type StatsTopTracksParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopTracksRow struct {
	CatalogID  string          `json:"catalog_id"`
	Title      string          `json:"title"`
	Artist     string          `json:"artist"`
	Album      string          `json:"album"`
	Source     string          `json:"source"`
	ExternalID string          `json:"external_id"`
	Plays      int64           `json:"plays"`
	MsPlayed   sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopTracks(ctx context.Context, arg StatsTopTracksParams) ([]StatsTopTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopTracks,
		arg.UserID,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopTracksRow
	for rows.Next() {
		var i StatsTopTracksRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Source,
			&i.ExternalID,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopTracksByAlbum = `-- name: StatsTopTracksByAlbum :many
SELECT
    p.catalog_id,
    e.title,
    e.artist,
    e.album,
    COUNT(*)          AS plays,
    SUM(p.ms_played)  AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND e.album = ? AND e.artist = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
GROUP BY p.catalog_id
ORDER BY COUNT(*) DESC, SUM(p.ms_played) DESC
LIMIT ?
`

type StatsTopTracksByAlbumParams struct {
	UserID     string `json:"user_id"`
	Album      string `json:"album"`
	Artist     string `json:"artist"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopTracksByAlbumRow struct {
	CatalogID string          `json:"catalog_id"`
	Title     string          `json:"title"`
	Artist    string          `json:"artist"`
	Album     string          `json:"album"`
	Plays     int64           `json:"plays"`
	MsPlayed  sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopTracksByAlbum(ctx context.Context, arg StatsTopTracksByAlbumParams) ([]StatsTopTracksByAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopTracksByAlbum,
		arg.UserID,
		arg.Album,
		arg.Artist,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopTracksByAlbumRow
	for rows.Next() {
		var i StatsTopTracksByAlbumRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopTracksByArtist = `-- name: StatsTopTracksByArtist :many
SELECT
    p.catalog_id,
    e.title,
    e.artist,
    e.album,
    COUNT(*)          AS plays,
    SUM(p.ms_played)  AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND e.artist = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
GROUP BY p.catalog_id
ORDER BY COUNT(*) DESC, SUM(p.ms_played) DESC
LIMIT ?
`

type StatsTopTracksByArtistParams struct {
	UserID     string `json:"user_id"`
	Artist     string `json:"artist"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopTracksByArtistRow struct {
	CatalogID string          `json:"catalog_id"`
	Title     string          `json:"title"`
	Artist    string          `json:"artist"`
	Album     string          `json:"album"`
	Plays     int64           `json:"plays"`
	MsPlayed  sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopTracksByArtist(ctx context.Context, arg StatsTopTracksByArtistParams) ([]StatsTopTracksByArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopTracksByArtist,
		arg.UserID,
		arg.Artist,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopTracksByArtistRow
	for rows.Next() {
		var i StatsTopTracksByArtistRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopTracksByCatalogID = `-- name: StatsTopTracksByCatalogID :many
SELECT
    p.catalog_id,
    e.title,
    e.artist,
    e.album,
    COUNT(*)          AS plays,
    SUM(p.ms_played)  AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.catalog_id = ? AND p.played_at >= ? AND p.played_at < ? AND p.qualified = 1
GROUP BY p.catalog_id
ORDER BY COUNT(*) DESC, SUM(p.ms_played) DESC
LIMIT ?
`

type StatsTopTracksByCatalogIDParams struct {
	UserID     string `json:"user_id"`
	CatalogID  string `json:"catalog_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopTracksByCatalogIDRow struct {
	CatalogID string          `json:"catalog_id"`
	Title     string          `json:"title"`
	Artist    string          `json:"artist"`
	Album     string          `json:"album"`
	Plays     int64           `json:"plays"`
	MsPlayed  sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopTracksByCatalogID(ctx context.Context, arg StatsTopTracksByCatalogIDParams) ([]StatsTopTracksByCatalogIDRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopTracksByCatalogID,
		arg.UserID,
		arg.CatalogID,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopTracksByCatalogIDRow
	for rows.Next() {
		var i StatsTopTracksByCatalogIDRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPlayedArtistsBetween = `-- name: TopPlayedArtistsBetween :many
SELECT CAST(MIN(e.artist) AS TEXT) AS artist, COUNT(*) AS plays
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.played_at >= ?1 AND p.played_at < ?2 AND p.qualified = 1
  AND e.artist != ''
GROUP BY lower(e.artist)
ORDER BY plays DESC, lower(MIN(e.artist))
LIMIT ?3
`

type TopPlayedArtistsBetweenParams struct {
	Since       int64 `json:"since"`
	Until       int64 `json:"until"`
	ResultLimit int64 `json:"result_limit"`
}

type TopPlayedArtistsBetweenRow struct {
	Artist string `json:"artist"`
	Plays  int64  `json:"plays"`
}

func (q *Queries) TopPlayedArtistsBetween(ctx context.Context, arg TopPlayedArtistsBetweenParams) ([]TopPlayedArtistsBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, topPlayedArtistsBetween, arg.Since, arg.Until, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopPlayedArtistsBetweenRow
	for rows.Next() {
		var i TopPlayedArtistsBetweenRow
		if err := rows.Scan(&i.Artist, &i.Plays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const topPlayedTracksBetween = `-- name: TopPlayedTracksBetween :many
SELECT CAST(MIN(e.title) AS TEXT) AS title, CAST(MIN(e.artist) AS TEXT) AS artist, COUNT(*) AS plays
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.played_at >= ?1 AND p.played_at < ?2 AND p.qualified = 1
  AND e.title != '' AND e.artist != ''
GROUP BY lower(e.artist), lower(e.title)
ORDER BY plays DESC, lower(MIN(e.artist)), lower(MIN(e.title))
LIMIT ?3
`

type TopPlayedTracksBetweenParams struct {
	Since       int64 `json:"since"`
	Until       int64 `json:"until"`
	ResultLimit int64 `json:"result_limit"`
}

type TopPlayedTracksBetweenRow struct {
	Title  string `json:"title"`
	Artist string `json:"artist"`
	Plays  int64  `json:"plays"`
}

func (q *Queries) TopPlayedTracksBetween(ctx context.Context, arg TopPlayedTracksBetweenParams) ([]TopPlayedTracksBetweenRow, error) {
	rows, err := q.db.QueryContext(ctx, topPlayedTracksBetween, arg.Since, arg.Until, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TopPlayedTracksBetweenRow
	for rows.Next() {
		var i TopPlayedTracksBetweenRow
		if err := rows.Scan(&i.Title, &i.Artist, &i.Plays); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
