// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: plays.sql

package db

import (
	"context"
	"database/sql"
)

const countPlaysByCatalog = `-- name: CountPlaysByCatalog :one
SELECT COUNT(*) FROM plays WHERE user_id = ? AND catalog_id = ?
`

type CountPlaysByCatalogParams struct {
	UserID    string `json:"user_id"`
	CatalogID string `json:"catalog_id"`
}

func (q *Queries) CountPlaysByCatalog(ctx context.Context, arg CountPlaysByCatalogParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPlaysByCatalog, arg.UserID, arg.CatalogID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePlay = `-- name: DeletePlay :exec
DELETE FROM plays WHERE id = ? AND user_id = ?
`

type DeletePlayParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeletePlay(ctx context.Context, arg DeletePlayParams) error {
	_, err := q.db.ExecContext(ctx, deletePlay, arg.ID, arg.UserID)
	return err
}

const distinctDurableCanonicalIDs = `-- name: DistinctDurableCanonicalIDs :many
SELECT DISTINCT catalog_id FROM plays WHERE catalog_id != ''
UNION
SELECT DISTINCT canonical_id FROM download_jobs WHERE canonical_id != ''
LIMIT ?
`

func (q *Queries) DistinctDurableCanonicalIDs(ctx context.Context, limit int64) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, distinctDurableCanonicalIDs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var catalog_id string
		if err := rows.Scan(&catalog_id); err != nil {
			return nil, err
		}
		items = append(items, catalog_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPlay = `-- name: InsertPlay :exec
INSERT INTO plays (id, user_id, catalog_id, played_at, ms_played, completed, created_at)
VALUES (?,?,?,?,?,?,?)
`

type InsertPlayParams struct {
	ID        string `json:"id"`
	UserID    string `json:"user_id"`
	CatalogID string `json:"catalog_id"`
	PlayedAt  int64  `json:"played_at"`
	MsPlayed  int64  `json:"ms_played"`
	Completed int64  `json:"completed"`
	CreatedAt int64  `json:"created_at"`
}

func (q *Queries) InsertPlay(ctx context.Context, arg InsertPlayParams) error {
	_, err := q.db.ExecContext(ctx, insertPlay,
		arg.ID,
		arg.UserID,
		arg.CatalogID,
		arg.PlayedAt,
		arg.MsPlayed,
		arg.Completed,
		arg.CreatedAt,
	)
	return err
}

const listRecentPlays = `-- name: ListRecentPlays :many
SELECT p.id, p.catalog_id, p.played_at, e.title, e.artist, e.album
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.played_at < ?
ORDER BY p.played_at DESC LIMIT ?
`

type ListRecentPlaysParams struct {
	UserID   string `json:"user_id"`
	PlayedAt int64  `json:"played_at"`
	Limit    int64  `json:"limit"`
}

type ListRecentPlaysRow struct {
	ID        string `json:"id"`
	CatalogID string `json:"catalog_id"`
	PlayedAt  int64  `json:"played_at"`
	Title     string `json:"title"`
	Artist    string `json:"artist"`
	Album     string `json:"album"`
}

func (q *Queries) ListRecentPlays(ctx context.Context, arg ListRecentPlaysParams) ([]ListRecentPlaysRow, error) {
	rows, err := q.db.QueryContext(ctx, listRecentPlays, arg.UserID, arg.PlayedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRecentPlaysRow
	for rows.Next() {
		var i ListRecentPlaysRow
		if err := rows.Scan(
			&i.ID,
			&i.CatalogID,
			&i.PlayedAt,
			&i.Title,
			&i.Artist,
			&i.Album,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointPlays = `-- name: RepointPlays :exec
UPDATE plays SET catalog_id = ? WHERE catalog_id = ?
`

type RepointPlaysParams struct {
	CatalogID   string `json:"catalog_id"`
	CatalogID_2 string `json:"catalog_id_2"`
}

func (q *Queries) RepointPlays(ctx context.Context, arg RepointPlaysParams) error {
	_, err := q.db.ExecContext(ctx, repointPlays, arg.CatalogID, arg.CatalogID_2)
	return err
}

const statsEntityAlbum = `-- name: StatsEntityAlbum :one
SELECT
    COUNT(*)         AS plays,
    COALESCE(SUM(p.ms_played), 0) AS ms_played,
    MIN(p.played_at) AS first_played,
    MAX(p.played_at) AS last_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND e.album = ? AND e.artist = ? AND p.played_at >= ? AND p.played_at < ?
`

type StatsEntityAlbumParams struct {
	UserID     string `json:"user_id"`
	Album      string `json:"album"`
	Artist     string `json:"artist"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsEntityAlbumRow struct {
	Plays       int64       `json:"plays"`
	MsPlayed    interface{} `json:"ms_played"`
	FirstPlayed interface{} `json:"first_played"`
	LastPlayed  interface{} `json:"last_played"`
}

func (q *Queries) StatsEntityAlbum(ctx context.Context, arg StatsEntityAlbumParams) (StatsEntityAlbumRow, error) {
	row := q.db.QueryRowContext(ctx, statsEntityAlbum,
		arg.UserID,
		arg.Album,
		arg.Artist,
		arg.PlayedAt,
		arg.PlayedAt_2,
	)
	var i StatsEntityAlbumRow
	err := row.Scan(
		&i.Plays,
		&i.MsPlayed,
		&i.FirstPlayed,
		&i.LastPlayed,
	)
	return i, err
}

const statsEntityArtist = `-- name: StatsEntityArtist :one
SELECT
    COUNT(*)         AS plays,
    COALESCE(SUM(p.ms_played), 0) AS ms_played,
    MIN(p.played_at) AS first_played,
    MAX(p.played_at) AS last_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND e.artist = ? AND p.played_at >= ? AND p.played_at < ?
`

type StatsEntityArtistParams struct {
	UserID     string `json:"user_id"`
	Artist     string `json:"artist"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsEntityArtistRow struct {
	Plays       int64       `json:"plays"`
	MsPlayed    interface{} `json:"ms_played"`
	FirstPlayed interface{} `json:"first_played"`
	LastPlayed  interface{} `json:"last_played"`
}

func (q *Queries) StatsEntityArtist(ctx context.Context, arg StatsEntityArtistParams) (StatsEntityArtistRow, error) {
	row := q.db.QueryRowContext(ctx, statsEntityArtist,
		arg.UserID,
		arg.Artist,
		arg.PlayedAt,
		arg.PlayedAt_2,
	)
	var i StatsEntityArtistRow
	err := row.Scan(
		&i.Plays,
		&i.MsPlayed,
		&i.FirstPlayed,
		&i.LastPlayed,
	)
	return i, err
}

const statsEntityTrack = `-- name: StatsEntityTrack :one
SELECT
    COUNT(*)         AS plays,
    COALESCE(SUM(p.ms_played), 0) AS ms_played,
    MIN(p.played_at) AS first_played,
    MAX(p.played_at) AS last_played
FROM plays p
WHERE p.user_id = ? AND p.catalog_id = ? AND p.played_at >= ? AND p.played_at < ?
`

type StatsEntityTrackParams struct {
	UserID     string `json:"user_id"`
	CatalogID  string `json:"catalog_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsEntityTrackRow struct {
	Plays       int64       `json:"plays"`
	MsPlayed    interface{} `json:"ms_played"`
	FirstPlayed interface{} `json:"first_played"`
	LastPlayed  interface{} `json:"last_played"`
}

func (q *Queries) StatsEntityTrack(ctx context.Context, arg StatsEntityTrackParams) (StatsEntityTrackRow, error) {
	row := q.db.QueryRowContext(ctx, statsEntityTrack,
		arg.UserID,
		arg.CatalogID,
		arg.PlayedAt,
		arg.PlayedAt_2,
	)
	var i StatsEntityTrackRow
	err := row.Scan(
		&i.Plays,
		&i.MsPlayed,
		&i.FirstPlayed,
		&i.LastPlayed,
	)
	return i, err
}

const statsPlaysInWindow = `-- name: StatsPlaysInWindow :many
SELECT p.played_at, p.ms_played
FROM plays p
WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ?
ORDER BY p.played_at ASC
`

type StatsPlaysInWindowParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsPlaysInWindowRow struct {
	PlayedAt int64 `json:"played_at"`
	MsPlayed int64 `json:"ms_played"`
}

func (q *Queries) StatsPlaysInWindow(ctx context.Context, arg StatsPlaysInWindowParams) ([]StatsPlaysInWindowRow, error) {
	rows, err := q.db.QueryContext(ctx, statsPlaysInWindow, arg.UserID, arg.PlayedAt, arg.PlayedAt_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsPlaysInWindowRow
	for rows.Next() {
		var i StatsPlaysInWindowRow
		if err := rows.Scan(&i.PlayedAt, &i.MsPlayed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsSummary = `-- name: StatsSummary :one
SELECT
    COUNT(*)                    AS plays,
    COUNT(DISTINCT p.catalog_id) AS distinct_tracks,
    COUNT(DISTINCT e.artist)    AS distinct_artists,
    COUNT(DISTINCT e.album)     AS distinct_albums,
    COALESCE(SUM(p.ms_played), 0) AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ?
`

type StatsSummaryParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
}

type StatsSummaryRow struct {
	Plays           int64       `json:"plays"`
	DistinctTracks  int64       `json:"distinct_tracks"`
	DistinctArtists int64       `json:"distinct_artists"`
	DistinctAlbums  int64       `json:"distinct_albums"`
	MsPlayed        interface{} `json:"ms_played"`
}

func (q *Queries) StatsSummary(ctx context.Context, arg StatsSummaryParams) (StatsSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, statsSummary, arg.UserID, arg.PlayedAt, arg.PlayedAt_2)
	var i StatsSummaryRow
	err := row.Scan(
		&i.Plays,
		&i.DistinctTracks,
		&i.DistinctArtists,
		&i.DistinctAlbums,
		&i.MsPlayed,
	)
	return i, err
}

const statsTopAlbums = `-- name: StatsTopAlbums :many
WITH aggregated AS (
    SELECT
        MIN(p.catalog_id) AS catalog_id,
        e.album,
        e.artist,
        COUNT(*)         AS plays,
        SUM(p.ms_played) AS ms_played
    FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
    WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ?
    GROUP BY e.album, e.artist
)
SELECT
    CAST(a.catalog_id AS TEXT) AS catalog_id,
    e.title,
    a.album,
    a.artist,
    CAST(e.source AS TEXT) AS source,
    CAST(e.external_id AS TEXT) AS external_id,
    a.plays,
    a.ms_played
FROM aggregated a JOIN catalog_entity e ON e.id = a.catalog_id
ORDER BY a.plays DESC, a.ms_played DESC
LIMIT ?
`

type StatsTopAlbumsParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopAlbumsRow struct {
	CatalogID  string          `json:"catalog_id"`
	Title      string          `json:"title"`
	Album      string          `json:"album"`
	Artist     string          `json:"artist"`
	Source     string          `json:"source"`
	ExternalID string          `json:"external_id"`
	Plays      int64           `json:"plays"`
	MsPlayed   sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopAlbums(ctx context.Context, arg StatsTopAlbumsParams) ([]StatsTopAlbumsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopAlbums,
		arg.UserID,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopAlbumsRow
	for rows.Next() {
		var i StatsTopAlbumsRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Album,
			&i.Artist,
			&i.Source,
			&i.ExternalID,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopArtists = `-- name: StatsTopArtists :many
WITH aggregated AS (
    SELECT
        MIN(p.catalog_id) AS catalog_id,
        e.artist,
        COUNT(*)         AS plays,
        SUM(p.ms_played) AS ms_played
    FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
    WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ?
    GROUP BY e.artist
)
SELECT
    CAST(a.catalog_id AS TEXT) AS catalog_id,
    e.title,
    a.artist,
    e.album,
    CAST(e.source AS TEXT) AS source,
    CAST(e.external_id AS TEXT) AS external_id,
    a.plays,
    a.ms_played
FROM aggregated a JOIN catalog_entity e ON e.id = a.catalog_id
ORDER BY a.plays DESC, a.ms_played DESC
LIMIT ?
`

type StatsTopArtistsParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopArtistsRow struct {
	CatalogID  string          `json:"catalog_id"`
	Title      string          `json:"title"`
	Artist     string          `json:"artist"`
	Album      string          `json:"album"`
	Source     string          `json:"source"`
	ExternalID string          `json:"external_id"`
	Plays      int64           `json:"plays"`
	MsPlayed   sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopArtists(ctx context.Context, arg StatsTopArtistsParams) ([]StatsTopArtistsRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopArtists,
		arg.UserID,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopArtistsRow
	for rows.Next() {
		var i StatsTopArtistsRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Source,
			&i.ExternalID,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopTracks = `-- name: StatsTopTracks :many
SELECT
    p.catalog_id,
    e.title,
    e.artist,
    e.album,
    e.source,
    e.external_id,
    COUNT(*)          AS plays,
    SUM(p.ms_played)  AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.played_at >= ? AND p.played_at < ?
GROUP BY p.catalog_id
ORDER BY COUNT(*) DESC, SUM(p.ms_played) DESC
LIMIT ?
`

type StatsTopTracksParams struct {
	UserID     string `json:"user_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopTracksRow struct {
	CatalogID  string          `json:"catalog_id"`
	Title      string          `json:"title"`
	Artist     string          `json:"artist"`
	Album      string          `json:"album"`
	Source     string          `json:"source"`
	ExternalID string          `json:"external_id"`
	Plays      int64           `json:"plays"`
	MsPlayed   sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopTracks(ctx context.Context, arg StatsTopTracksParams) ([]StatsTopTracksRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopTracks,
		arg.UserID,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopTracksRow
	for rows.Next() {
		var i StatsTopTracksRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Source,
			&i.ExternalID,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopTracksByAlbum = `-- name: StatsTopTracksByAlbum :many
SELECT
    p.catalog_id,
    e.title,
    e.artist,
    e.album,
    COUNT(*)          AS plays,
    SUM(p.ms_played)  AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND e.album = ? AND e.artist = ? AND p.played_at >= ? AND p.played_at < ?
GROUP BY p.catalog_id
ORDER BY COUNT(*) DESC, SUM(p.ms_played) DESC
LIMIT ?
`

type StatsTopTracksByAlbumParams struct {
	UserID     string `json:"user_id"`
	Album      string `json:"album"`
	Artist     string `json:"artist"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopTracksByAlbumRow struct {
	CatalogID string          `json:"catalog_id"`
	Title     string          `json:"title"`
	Artist    string          `json:"artist"`
	Album     string          `json:"album"`
	Plays     int64           `json:"plays"`
	MsPlayed  sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopTracksByAlbum(ctx context.Context, arg StatsTopTracksByAlbumParams) ([]StatsTopTracksByAlbumRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopTracksByAlbum,
		arg.UserID,
		arg.Album,
		arg.Artist,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopTracksByAlbumRow
	for rows.Next() {
		var i StatsTopTracksByAlbumRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopTracksByArtist = `-- name: StatsTopTracksByArtist :many
SELECT
    p.catalog_id,
    e.title,
    e.artist,
    e.album,
    COUNT(*)          AS plays,
    SUM(p.ms_played)  AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND e.artist = ? AND p.played_at >= ? AND p.played_at < ?
GROUP BY p.catalog_id
ORDER BY COUNT(*) DESC, SUM(p.ms_played) DESC
LIMIT ?
`

type StatsTopTracksByArtistParams struct {
	UserID     string `json:"user_id"`
	Artist     string `json:"artist"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopTracksByArtistRow struct {
	CatalogID string          `json:"catalog_id"`
	Title     string          `json:"title"`
	Artist    string          `json:"artist"`
	Album     string          `json:"album"`
	Plays     int64           `json:"plays"`
	MsPlayed  sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopTracksByArtist(ctx context.Context, arg StatsTopTracksByArtistParams) ([]StatsTopTracksByArtistRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopTracksByArtist,
		arg.UserID,
		arg.Artist,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopTracksByArtistRow
	for rows.Next() {
		var i StatsTopTracksByArtistRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const statsTopTracksByCatalogID = `-- name: StatsTopTracksByCatalogID :many
SELECT
    p.catalog_id,
    e.title,
    e.artist,
    e.album,
    COUNT(*)          AS plays,
    SUM(p.ms_played)  AS ms_played
FROM plays p JOIN catalog_entity e ON e.id = p.catalog_id
WHERE p.user_id = ? AND p.catalog_id = ? AND p.played_at >= ? AND p.played_at < ?
GROUP BY p.catalog_id
ORDER BY COUNT(*) DESC, SUM(p.ms_played) DESC
LIMIT ?
`

type StatsTopTracksByCatalogIDParams struct {
	UserID     string `json:"user_id"`
	CatalogID  string `json:"catalog_id"`
	PlayedAt   int64  `json:"played_at"`
	PlayedAt_2 int64  `json:"played_at_2"`
	Limit      int64  `json:"limit"`
}

type StatsTopTracksByCatalogIDRow struct {
	CatalogID string          `json:"catalog_id"`
	Title     string          `json:"title"`
	Artist    string          `json:"artist"`
	Album     string          `json:"album"`
	Plays     int64           `json:"plays"`
	MsPlayed  sql.NullFloat64 `json:"ms_played"`
}

func (q *Queries) StatsTopTracksByCatalogID(ctx context.Context, arg StatsTopTracksByCatalogIDParams) ([]StatsTopTracksByCatalogIDRow, error) {
	rows, err := q.db.QueryContext(ctx, statsTopTracksByCatalogID,
		arg.UserID,
		arg.CatalogID,
		arg.PlayedAt,
		arg.PlayedAt_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StatsTopTracksByCatalogIDRow
	for rows.Next() {
		var i StatsTopTracksByCatalogIDRow
		if err := rows.Scan(
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.Plays,
			&i.MsPlayed,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
