// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: scrobble.sql

package db

import (
	"context"
)

const countScrobbleLinksByProvider = `-- name: CountScrobbleLinksByProvider :one
SELECT COUNT(*) FROM scrobble_link
WHERE provider = ?
`

func (q *Queries) CountScrobbleLinksByProvider(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countScrobbleLinksByProvider, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePendingScrobbles = `-- name: DeletePendingScrobbles :exec
DELETE FROM scrobble_queue
WHERE user_id = ? AND provider = ? AND status = 'pending'
`

type DeletePendingScrobblesParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeletePendingScrobbles(ctx context.Context, arg DeletePendingScrobblesParams) error {
	_, err := q.db.ExecContext(ctx, deletePendingScrobbles, arg.UserID, arg.Provider)
	return err
}

const deleteScrobbleLink = `-- name: DeleteScrobbleLink :exec
DELETE FROM scrobble_link
WHERE user_id = ? AND provider = ?
`

type DeleteScrobbleLinkParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteScrobbleLink(ctx context.Context, arg DeleteScrobbleLinkParams) error {
	_, err := q.db.ExecContext(ctx, deleteScrobbleLink, arg.UserID, arg.Provider)
	return err
}

const getScrobbleLink = `-- name: GetScrobbleLink :one
SELECT user_id, provider, session_key, username, status, created_at
FROM scrobble_link
WHERE user_id = ? AND provider = ?
`

type GetScrobbleLinkParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetScrobbleLink(ctx context.Context, arg GetScrobbleLinkParams) (ScrobbleLink, error) {
	row := q.db.QueryRowContext(ctx, getScrobbleLink, arg.UserID, arg.Provider)
	var i ScrobbleLink
	err := row.Scan(
		&i.UserID,
		&i.Provider,
		&i.SessionKey,
		&i.Username,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const insertScrobbleQueue = `-- name: InsertScrobbleQueue :exec
INSERT INTO scrobble_queue (id, user_id, provider, catalog_id, title, artist, album, duration_ms, played_at, status, attempts, next_attempt_at, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertScrobbleQueueParams struct {
	ID            string `json:"id"`
	UserID        string `json:"user_id"`
	Provider      string `json:"provider"`
	CatalogID     string `json:"catalog_id"`
	Title         string `json:"title"`
	Artist        string `json:"artist"`
	Album         string `json:"album"`
	DurationMs    int64  `json:"duration_ms"`
	PlayedAt      int64  `json:"played_at"`
	Status        string `json:"status"`
	Attempts      int64  `json:"attempts"`
	NextAttemptAt int64  `json:"next_attempt_at"`
	CreatedAt     int64  `json:"created_at"`
}

func (q *Queries) InsertScrobbleQueue(ctx context.Context, arg InsertScrobbleQueueParams) error {
	_, err := q.db.ExecContext(ctx, insertScrobbleQueue,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.CatalogID,
		arg.Title,
		arg.Artist,
		arg.Album,
		arg.DurationMs,
		arg.PlayedAt,
		arg.Status,
		arg.Attempts,
		arg.NextAttemptAt,
		arg.CreatedAt,
	)
	return err
}

const listActiveScrobbleLinksByProvider = `-- name: ListActiveScrobbleLinksByProvider :many
SELECT user_id, provider, session_key, username, status, created_at
FROM scrobble_link
WHERE provider = ? AND status = 'active'
ORDER BY created_at, user_id
`

func (q *Queries) ListActiveScrobbleLinksByProvider(ctx context.Context, provider string) ([]ScrobbleLink, error) {
	rows, err := q.db.QueryContext(ctx, listActiveScrobbleLinksByProvider, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScrobbleLink
	for rows.Next() {
		var i ScrobbleLink
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.SessionKey,
			&i.Username,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScrobbleLinks = `-- name: ListScrobbleLinks :many
SELECT user_id, provider, session_key, username, status, created_at
FROM scrobble_link
WHERE user_id = ?
ORDER BY provider
`

func (q *Queries) ListScrobbleLinks(ctx context.Context, userID string) ([]ScrobbleLink, error) {
	rows, err := q.db.QueryContext(ctx, listScrobbleLinks, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScrobbleLink
	for rows.Next() {
		var i ScrobbleLink
		if err := rows.Scan(
			&i.UserID,
			&i.Provider,
			&i.SessionKey,
			&i.Username,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSentScrobbles = `-- name: ListSentScrobbles :many
SELECT artist, title, played_at
FROM scrobble_queue
WHERE provider = ? AND status = 'done'
`

type ListSentScrobblesRow struct {
	Artist   string `json:"artist"`
	Title    string `json:"title"`
	PlayedAt int64  `json:"played_at"`
}

func (q *Queries) ListSentScrobbles(ctx context.Context, provider string) ([]ListSentScrobblesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSentScrobbles, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSentScrobblesRow
	for rows.Next() {
		var i ListSentScrobblesRow
		if err := rows.Scan(&i.Artist, &i.Title, &i.PlayedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markScrobbleDone = `-- name: MarkScrobbleDone :exec
UPDATE scrobble_queue
SET status = 'done'
WHERE id = ?
`

func (q *Queries) MarkScrobbleDone(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markScrobbleDone, id)
	return err
}

const markScrobbleFailed = `-- name: MarkScrobbleFailed :exec
UPDATE scrobble_queue
SET status = 'failed'
WHERE id = ?
`

func (q *Queries) MarkScrobbleFailed(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markScrobbleFailed, id)
	return err
}

const markScrobbleRetry = `-- name: MarkScrobbleRetry :exec
UPDATE scrobble_queue
SET attempts = ?, next_attempt_at = ?
WHERE id = ?
`

type MarkScrobbleRetryParams struct {
	Attempts      int64  `json:"attempts"`
	NextAttemptAt int64  `json:"next_attempt_at"`
	ID            string `json:"id"`
}

func (q *Queries) MarkScrobbleRetry(ctx context.Context, arg MarkScrobbleRetryParams) error {
	_, err := q.db.ExecContext(ctx, markScrobbleRetry, arg.Attempts, arg.NextAttemptAt, arg.ID)
	return err
}

const selectDueScrobbles = `-- name: SelectDueScrobbles :many
SELECT id, user_id, provider, catalog_id, title, artist, album, duration_ms, played_at, status, attempts, next_attempt_at, created_at
FROM scrobble_queue
WHERE status = 'pending' AND next_attempt_at <= ?
ORDER BY next_attempt_at
LIMIT ?
`

type SelectDueScrobblesParams struct {
	NextAttemptAt int64 `json:"next_attempt_at"`
	Limit         int64 `json:"limit"`
}

func (q *Queries) SelectDueScrobbles(ctx context.Context, arg SelectDueScrobblesParams) ([]ScrobbleQueue, error) {
	rows, err := q.db.QueryContext(ctx, selectDueScrobbles, arg.NextAttemptAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScrobbleQueue
	for rows.Next() {
		var i ScrobbleQueue
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.CatalogID,
			&i.Title,
			&i.Artist,
			&i.Album,
			&i.DurationMs,
			&i.PlayedAt,
			&i.Status,
			&i.Attempts,
			&i.NextAttemptAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setScrobbleLinkStatus = `-- name: SetScrobbleLinkStatus :exec
UPDATE scrobble_link
SET status = ?
WHERE user_id = ? AND provider = ?
`

type SetScrobbleLinkStatusParams struct {
	Status   string `json:"status"`
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) SetScrobbleLinkStatus(ctx context.Context, arg SetScrobbleLinkStatusParams) error {
	_, err := q.db.ExecContext(ctx, setScrobbleLinkStatus, arg.Status, arg.UserID, arg.Provider)
	return err
}

const upsertScrobbleLink = `-- name: UpsertScrobbleLink :exec
INSERT INTO scrobble_link (user_id, provider, session_key, username, status, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT (user_id, provider) DO UPDATE SET
  session_key = excluded.session_key,
  username    = excluded.username,
  status      = excluded.status
`

type UpsertScrobbleLinkParams struct {
	UserID     string `json:"user_id"`
	Provider   string `json:"provider"`
	SessionKey string `json:"session_key"`
	Username   string `json:"username"`
	Status     string `json:"status"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) UpsertScrobbleLink(ctx context.Context, arg UpsertScrobbleLinkParams) error {
	_, err := q.db.ExecContext(ctx, upsertScrobbleLink,
		arg.UserID,
		arg.Provider,
		arg.SessionKey,
		arg.Username,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}
