// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: sync.sql

package db

import (
	"context"
)

const appendSyncChange = `-- name: AppendSyncChange :one
INSERT INTO sync_change (device_id, entity_type, entity_id, field, value_json, updated_at) VALUES (?, ?, ?, ?, ?, ?) RETURNING revision
`

type AppendSyncChangeParams struct {
	DeviceID   string `json:"device_id"`
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Field      string `json:"field"`
	ValueJson  string `json:"value_json"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) AppendSyncChange(ctx context.Context, arg AppendSyncChangeParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, appendSyncChange,
		arg.DeviceID,
		arg.EntityType,
		arg.EntityID,
		arg.Field,
		arg.ValueJson,
		arg.UpdatedAt,
	)
	var revision int64
	err := row.Scan(&revision)
	return revision, err
}

const countSyncChanges = `-- name: CountSyncChanges :one
SELECT COUNT(*) FROM sync_change
`

func (q *Queries) CountSyncChanges(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSyncChanges)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteSyncCursor = `-- name: DeleteSyncCursor :exec
DELETE FROM sync_cursor WHERE device_id = ?
`

func (q *Queries) DeleteSyncCursor(ctx context.Context, deviceID string) error {
	_, err := q.db.ExecContext(ctx, deleteSyncCursor, deviceID)
	return err
}

const getLatestSyncChangeForField = `-- name: GetLatestSyncChangeForField :one
SELECT revision, device_id, entity_type, entity_id, field, value_json, updated_at, created_at FROM sync_change WHERE entity_type = ? AND entity_id = ? AND field = ? ORDER BY revision DESC LIMIT 1
`

type GetLatestSyncChangeForFieldParams struct {
	EntityType string `json:"entity_type"`
	EntityID   string `json:"entity_id"`
	Field      string `json:"field"`
}

func (q *Queries) GetLatestSyncChangeForField(ctx context.Context, arg GetLatestSyncChangeForFieldParams) (SyncChange, error) {
	row := q.db.QueryRowContext(ctx, getLatestSyncChangeForField, arg.EntityType, arg.EntityID, arg.Field)
	var i SyncChange
	err := row.Scan(
		&i.Revision,
		&i.DeviceID,
		&i.EntityType,
		&i.EntityID,
		&i.Field,
		&i.ValueJson,
		&i.UpdatedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getMaxSyncRevision = `-- name: GetMaxSyncRevision :one
SELECT COALESCE(MAX(revision), 0) AS max_revision FROM sync_change
`

func (q *Queries) GetMaxSyncRevision(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getMaxSyncRevision)
	var max_revision interface{}
	err := row.Scan(&max_revision)
	return max_revision, err
}

const getSyncCursor = `-- name: GetSyncCursor :one
SELECT device_id, revision, updated_at FROM sync_cursor WHERE device_id = ?
`

func (q *Queries) GetSyncCursor(ctx context.Context, deviceID string) (SyncCursor, error) {
	row := q.db.QueryRowContext(ctx, getSyncCursor, deviceID)
	var i SyncCursor
	err := row.Scan(&i.DeviceID, &i.Revision, &i.UpdatedAt)
	return i, err
}

const listSyncChangesSince = `-- name: ListSyncChangesSince :many
SELECT revision, device_id, entity_type, entity_id, field, value_json, updated_at, created_at FROM sync_change WHERE revision > ? ORDER BY revision ASC LIMIT ?
`

type ListSyncChangesSinceParams struct {
	Revision int64 `json:"revision"`
	Limit    int64 `json:"limit"`
}

func (q *Queries) ListSyncChangesSince(ctx context.Context, arg ListSyncChangesSinceParams) ([]SyncChange, error) {
	rows, err := q.db.QueryContext(ctx, listSyncChangesSince, arg.Revision, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncChange
	for rows.Next() {
		var i SyncChange
		if err := rows.Scan(
			&i.Revision,
			&i.DeviceID,
			&i.EntityType,
			&i.EntityID,
			&i.Field,
			&i.ValueJson,
			&i.UpdatedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertSyncCursor = `-- name: UpsertSyncCursor :exec
INSERT INTO sync_cursor (device_id, revision, updated_at) VALUES (?, ?, unixepoch()) ON CONFLICT(device_id) DO UPDATE SET revision = excluded.revision, updated_at = unixepoch()
`

type UpsertSyncCursorParams struct {
	DeviceID string `json:"device_id"`
	Revision int64  `json:"revision"`
}

func (q *Queries) UpsertSyncCursor(ctx context.Context, arg UpsertSyncCursorParams) error {
	_, err := q.db.ExecContext(ctx, upsertSyncCursor, arg.DeviceID, arg.Revision)
	return err
}
