// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: synced_playlists.sql

package db

import (
	"context"
	"database/sql"
)

const backfillSyncedPlaylistOwners = `-- name: BackfillSyncedPlaylistOwners :exec
UPDATE synced_playlists SET owner_user_id = ? WHERE owner_user_id IS NULL
`

// Assigns the given owner to every playlist that has no owner yet. Used by the
// legacy single-admin migration in EnsureSeed (idempotent: only touches NULLs).
func (q *Queries) BackfillSyncedPlaylistOwners(ctx context.Context, ownerUserID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, backfillSyncedPlaylistOwners, ownerUserID)
	return err
}

const deleteSyncedPlaylist = `-- name: DeleteSyncedPlaylist :exec
DELETE FROM synced_playlists WHERE id = ?
`

func (q *Queries) DeleteSyncedPlaylist(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteSyncedPlaylist, id)
	return err
}

const getSyncedPlaylist = `-- name: GetSyncedPlaylist :one
SELECT id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at, mode, owner_user_id FROM synced_playlists WHERE id = ?
`

func (q *Queries) GetSyncedPlaylist(ctx context.Context, id string) (SyncedPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getSyncedPlaylist, id)
	var i SyncedPlaylist
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.CoverUrl,
		&i.TracksJson,
		&i.SyncEnabled,
		&i.SyncIntervalSec,
		&i.AutoDownload,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Mode,
		&i.OwnerUserID,
	)
	return i, err
}

const getSyncedPlaylistBySource = `-- name: GetSyncedPlaylistBySource :one
SELECT id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at, mode, owner_user_id FROM synced_playlists WHERE source = ? AND external_id = ?
`

type GetSyncedPlaylistBySourceParams struct {
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetSyncedPlaylistBySource(ctx context.Context, arg GetSyncedPlaylistBySourceParams) (SyncedPlaylist, error) {
	row := q.db.QueryRowContext(ctx, getSyncedPlaylistBySource, arg.Source, arg.ExternalID)
	var i SyncedPlaylist
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.CoverUrl,
		&i.TracksJson,
		&i.SyncEnabled,
		&i.SyncIntervalSec,
		&i.AutoDownload,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Mode,
		&i.OwnerUserID,
	)
	return i, err
}

const getSyncedPlaylistOwner = `-- name: GetSyncedPlaylistOwner :one
SELECT owner_user_id FROM synced_playlists WHERE id = ?
`

// Returns the owner_user_id for a playlist id (NULL when unowned/legacy). Used by
// the API mutation/detail handlers to enforce ownership (admins bypass).
func (q *Queries) GetSyncedPlaylistOwner(ctx context.Context, id string) (sql.NullString, error) {
	row := q.db.QueryRowContext(ctx, getSyncedPlaylistOwner, id)
	var owner_user_id sql.NullString
	err := row.Scan(&owner_user_id)
	return owner_user_id, err
}

const listDueSyncedPlaylists = `-- name: ListDueSyncedPlaylists :many
SELECT id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at, mode, owner_user_id FROM synced_playlists
WHERE sync_enabled = 1 AND sync_interval_sec > 0 AND (last_synced_at + sync_interval_sec) <= ?
`

func (q *Queries) ListDueSyncedPlaylists(ctx context.Context, lastSyncedAt int64) ([]SyncedPlaylist, error) {
	rows, err := q.db.QueryContext(ctx, listDueSyncedPlaylists, lastSyncedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncedPlaylist
	for rows.Next() {
		var i SyncedPlaylist
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Name,
			&i.CoverUrl,
			&i.TracksJson,
			&i.SyncEnabled,
			&i.SyncIntervalSec,
			&i.AutoDownload,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.Mode,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncedPlaylists = `-- name: ListSyncedPlaylists :many
SELECT id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at, mode, owner_user_id FROM synced_playlists ORDER BY created_at DESC
`

func (q *Queries) ListSyncedPlaylists(ctx context.Context) ([]SyncedPlaylist, error) {
	rows, err := q.db.QueryContext(ctx, listSyncedPlaylists)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SyncedPlaylist
	for rows.Next() {
		var i SyncedPlaylist
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Name,
			&i.CoverUrl,
			&i.TracksJson,
			&i.SyncEnabled,
			&i.SyncIntervalSec,
			&i.AutoDownload,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.Mode,
			&i.OwnerUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncedPlaylistsCount = `-- name: ListSyncedPlaylistsCount :many
SELECT id, source, external_id, name, cover_url, mode,
       sync_enabled, sync_interval_sec, auto_download,
       last_synced_at, created_at,
       CAST(json_array_length(tracks_json) AS INTEGER) AS track_count
FROM synced_playlists ORDER BY created_at DESC
`

type ListSyncedPlaylistsCountRow struct {
	ID              string `json:"id"`
	Source          string `json:"source"`
	ExternalID      string `json:"external_id"`
	Name            string `json:"name"`
	CoverUrl        string `json:"cover_url"`
	Mode            string `json:"mode"`
	SyncEnabled     int64  `json:"sync_enabled"`
	SyncIntervalSec int64  `json:"sync_interval_sec"`
	AutoDownload    int64  `json:"auto_download"`
	LastSyncedAt    int64  `json:"last_synced_at"`
	CreatedAt       int64  `json:"created_at"`
	TrackCount      int64  `json:"track_count"`
}

// Returns all playlists for the list view with track_count derived via
// json_array_length so the Go service never unmarshals the full tracks_json blob.
func (q *Queries) ListSyncedPlaylistsCount(ctx context.Context) ([]ListSyncedPlaylistsCountRow, error) {
	rows, err := q.db.QueryContext(ctx, listSyncedPlaylistsCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncedPlaylistsCountRow
	for rows.Next() {
		var i ListSyncedPlaylistsCountRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Name,
			&i.CoverUrl,
			&i.Mode,
			&i.SyncEnabled,
			&i.SyncIntervalSec,
			&i.AutoDownload,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSyncedPlaylistsCountForOwner = `-- name: ListSyncedPlaylistsCountForOwner :many
SELECT id, source, external_id, name, cover_url, mode,
       sync_enabled, sync_interval_sec, auto_download,
       last_synced_at, created_at,
       CAST(json_array_length(tracks_json) AS INTEGER) AS track_count
FROM synced_playlists WHERE owner_user_id = ? ORDER BY created_at DESC
`

type ListSyncedPlaylistsCountForOwnerRow struct {
	ID              string `json:"id"`
	Source          string `json:"source"`
	ExternalID      string `json:"external_id"`
	Name            string `json:"name"`
	CoverUrl        string `json:"cover_url"`
	Mode            string `json:"mode"`
	SyncEnabled     int64  `json:"sync_enabled"`
	SyncIntervalSec int64  `json:"sync_interval_sec"`
	AutoDownload    int64  `json:"auto_download"`
	LastSyncedAt    int64  `json:"last_synced_at"`
	CreatedAt       int64  `json:"created_at"`
	TrackCount      int64  `json:"track_count"`
}

// Owner-scoped variant of ListSyncedPlaylistsCount for the API list view:
// returns only playlists owned by the given user. Used by the API list handler
// for non-admin callers so the list is scoped to the caller's own playlists.
func (q *Queries) ListSyncedPlaylistsCountForOwner(ctx context.Context, ownerUserID sql.NullString) ([]ListSyncedPlaylistsCountForOwnerRow, error) {
	rows, err := q.db.QueryContext(ctx, listSyncedPlaylistsCountForOwner, ownerUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSyncedPlaylistsCountForOwnerRow
	for rows.Next() {
		var i ListSyncedPlaylistsCountForOwnerRow
		if err := rows.Scan(
			&i.ID,
			&i.Source,
			&i.ExternalID,
			&i.Name,
			&i.CoverUrl,
			&i.Mode,
			&i.SyncEnabled,
			&i.SyncIntervalSec,
			&i.AutoDownload,
			&i.LastSyncedAt,
			&i.CreatedAt,
			&i.TrackCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setSyncedPlaylistOwner = `-- name: SetSyncedPlaylistOwner :exec
UPDATE synced_playlists SET owner_user_id = ? WHERE id = ?
`

type SetSyncedPlaylistOwnerParams struct {
	OwnerUserID sql.NullString `json:"owner_user_id"`
	ID          string         `json:"id"`
}

// Stamps the owner on a freshly created playlist. Called by the API create/import
// handlers immediately after the playlist row is created.
func (q *Queries) SetSyncedPlaylistOwner(ctx context.Context, arg SetSyncedPlaylistOwnerParams) error {
	_, err := q.db.ExecContext(ctx, setSyncedPlaylistOwner, arg.OwnerUserID, arg.ID)
	return err
}

const updateSyncedPlaylistSettings = `-- name: UpdateSyncedPlaylistSettings :exec
UPDATE synced_playlists SET sync_enabled = ?, sync_interval_sec = ?, auto_download = ? WHERE id = ?
`

type UpdateSyncedPlaylistSettingsParams struct {
	SyncEnabled     int64  `json:"sync_enabled"`
	SyncIntervalSec int64  `json:"sync_interval_sec"`
	AutoDownload    int64  `json:"auto_download"`
	ID              string `json:"id"`
}

func (q *Queries) UpdateSyncedPlaylistSettings(ctx context.Context, arg UpdateSyncedPlaylistSettingsParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncedPlaylistSettings,
		arg.SyncEnabled,
		arg.SyncIntervalSec,
		arg.AutoDownload,
		arg.ID,
	)
	return err
}

const updateSyncedPlaylistTracks = `-- name: UpdateSyncedPlaylistTracks :exec
UPDATE synced_playlists SET name = ?, cover_url = ?, tracks_json = ?, last_synced_at = ? WHERE id = ?
`

type UpdateSyncedPlaylistTracksParams struct {
	Name         string `json:"name"`
	CoverUrl     string `json:"cover_url"`
	TracksJson   string `json:"tracks_json"`
	LastSyncedAt int64  `json:"last_synced_at"`
	ID           string `json:"id"`
}

func (q *Queries) UpdateSyncedPlaylistTracks(ctx context.Context, arg UpdateSyncedPlaylistTracksParams) error {
	_, err := q.db.ExecContext(ctx, updateSyncedPlaylistTracks,
		arg.Name,
		arg.CoverUrl,
		arg.TracksJson,
		arg.LastSyncedAt,
		arg.ID,
	)
	return err
}

const upsertSyncedPlaylist = `-- name: UpsertSyncedPlaylist :one
INSERT INTO synced_playlists (id, source, external_id, name, cover_url, tracks_json, mode, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(source, external_id) DO UPDATE SET
  name = excluded.name, cover_url = excluded.cover_url, tracks_json = excluded.tracks_json
RETURNING id, source, external_id, name, cover_url, tracks_json, sync_enabled, sync_interval_sec, auto_download, last_synced_at, created_at, mode, owner_user_id
`

type UpsertSyncedPlaylistParams struct {
	ID         string `json:"id"`
	Source     string `json:"source"`
	ExternalID string `json:"external_id"`
	Name       string `json:"name"`
	CoverUrl   string `json:"cover_url"`
	TracksJson string `json:"tracks_json"`
	Mode       string `json:"mode"`
	CreatedAt  int64  `json:"created_at"`
}

func (q *Queries) UpsertSyncedPlaylist(ctx context.Context, arg UpsertSyncedPlaylistParams) (SyncedPlaylist, error) {
	row := q.db.QueryRowContext(ctx, upsertSyncedPlaylist,
		arg.ID,
		arg.Source,
		arg.ExternalID,
		arg.Name,
		arg.CoverUrl,
		arg.TracksJson,
		arg.Mode,
		arg.CreatedAt,
	)
	var i SyncedPlaylist
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.ExternalID,
		&i.Name,
		&i.CoverUrl,
		&i.TracksJson,
		&i.SyncEnabled,
		&i.SyncIntervalSec,
		&i.AutoDownload,
		&i.LastSyncedAt,
		&i.CreatedAt,
		&i.Mode,
		&i.OwnerUserID,
	)
	return i, err
}
