// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: taste_history.sql

package db

import (
	"context"
)

const deleteTasteHistory = `-- name: DeleteTasteHistory :exec
DELETE FROM taste_history
WHERE provider = ?
`

func (q *Queries) DeleteTasteHistory(ctx context.Context, provider string) error {
	_, err := q.db.ExecContext(ctx, deleteTasteHistory, provider)
	return err
}

const insertTasteHistory = `-- name: InsertTasteHistory :exec
INSERT INTO taste_history (provider, artist, title, plays, at)
VALUES (?, ?, ?, ?, ?)
`

type InsertTasteHistoryParams struct {
	Provider string `json:"provider"`
	Artist   string `json:"artist"`
	Title    string `json:"title"`
	Plays    int64  `json:"plays"`
	At       int64  `json:"at"`
}

func (q *Queries) InsertTasteHistory(ctx context.Context, arg InsertTasteHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertTasteHistory,
		arg.Provider,
		arg.Artist,
		arg.Title,
		arg.Plays,
		arg.At,
	)
	return err
}

const listTasteHistory = `-- name: ListTasteHistory :many
SELECT provider, artist, title, plays, at
FROM taste_history
ORDER BY rowid
`

func (q *Queries) ListTasteHistory(ctx context.Context) ([]TasteHistory, error) {
	rows, err := q.db.QueryContext(ctx, listTasteHistory)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TasteHistory
	for rows.Next() {
		var i TasteHistory
		if err := rows.Scan(
			&i.Provider,
			&i.Artist,
			&i.Title,
			&i.Plays,
			&i.At,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
