// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: track_loudness.sql

package db

import (
	"context"
)

const deleteTrackLoudness = `-- name: DeleteTrackLoudness :exec
DELETE FROM track_loudness WHERE track_id = ?
`

func (q *Queries) DeleteTrackLoudness(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackLoudness, trackID)
	return err
}

const getTrackLoudness = `-- name: GetTrackLoudness :one
SELECT track_id, gain_db, updated_at FROM track_loudness WHERE track_id = ?
`

func (q *Queries) GetTrackLoudness(ctx context.Context, trackID string) (TrackLoudness, error) {
	row := q.db.QueryRowContext(ctx, getTrackLoudness, trackID)
	var i TrackLoudness
	err := row.Scan(&i.TrackID, &i.GainDb, &i.UpdatedAt)
	return i, err
}

const upsertTrackLoudness = `-- name: UpsertTrackLoudness :exec
INSERT INTO track_loudness (track_id, gain_db, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  gain_db = excluded.gain_db,
  updated_at = excluded.updated_at
`

type UpsertTrackLoudnessParams struct {
	TrackID   string  `json:"track_id"`
	GainDb    float64 `json:"gain_db"`
	UpdatedAt int64   `json:"updated_at"`
}

func (q *Queries) UpsertTrackLoudness(ctx context.Context, arg UpsertTrackLoudnessParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackLoudness, arg.TrackID, arg.GainDb, arg.UpdatedAt)
	return err
}
