// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: track_crop.sql

package db

import (
	"context"
	"database/sql"
)

const deleteTrackCrop = `-- name: DeleteTrackCrop :exec
DELETE FROM track_crop WHERE track_id = ?
`

func (q *Queries) DeleteTrackCrop(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackCrop, trackID)
	return err
}

const deleteTrackCropByCatalogID = `-- name: DeleteTrackCropByCatalogID :exec
DELETE FROM track_crop WHERE catalog_id = ?
`

func (q *Queries) DeleteTrackCropByCatalogID(ctx context.Context, catalogID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteTrackCropByCatalogID, catalogID)
	return err
}

const getTrackCrop = `-- name: GetTrackCrop :one
SELECT track_id, start_ms, end_ms, updated_at, catalog_id FROM track_crop WHERE track_id = ?
`

func (q *Queries) GetTrackCrop(ctx context.Context, trackID string) (TrackCrop, error) {
	row := q.db.QueryRowContext(ctx, getTrackCrop, trackID)
	var i TrackCrop
	err := row.Scan(
		&i.TrackID,
		&i.StartMs,
		&i.EndMs,
		&i.UpdatedAt,
		&i.CatalogID,
	)
	return i, err
}

const getTrackCropByCatalogID = `-- name: GetTrackCropByCatalogID :one
SELECT track_id, start_ms, end_ms, updated_at, catalog_id FROM track_crop WHERE catalog_id = ?
`

func (q *Queries) GetTrackCropByCatalogID(ctx context.Context, catalogID sql.NullString) (TrackCrop, error) {
	row := q.db.QueryRowContext(ctx, getTrackCropByCatalogID, catalogID)
	var i TrackCrop
	err := row.Scan(
		&i.TrackID,
		&i.StartMs,
		&i.EndMs,
		&i.UpdatedAt,
		&i.CatalogID,
	)
	return i, err
}

const listTrackCrops = `-- name: ListTrackCrops :many
SELECT track_id, start_ms, end_ms, updated_at, catalog_id FROM track_crop
`

func (q *Queries) ListTrackCrops(ctx context.Context) ([]TrackCrop, error) {
	rows, err := q.db.QueryContext(ctx, listTrackCrops)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackCrop
	for rows.Next() {
		var i TrackCrop
		if err := rows.Scan(
			&i.TrackID,
			&i.StartMs,
			&i.EndMs,
			&i.UpdatedAt,
			&i.CatalogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrackCrop = `-- name: UpsertTrackCrop :exec
INSERT INTO track_crop (track_id, start_ms, end_ms, updated_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  start_ms = excluded.start_ms,
  end_ms = excluded.end_ms,
  updated_at = excluded.updated_at
`

type UpsertTrackCropParams struct {
	TrackID   string        `json:"track_id"`
	StartMs   int64         `json:"start_ms"`
	EndMs     sql.NullInt64 `json:"end_ms"`
	UpdatedAt int64         `json:"updated_at"`
}

func (q *Queries) UpsertTrackCrop(ctx context.Context, arg UpsertTrackCropParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackCrop,
		arg.TrackID,
		arg.StartMs,
		arg.EndMs,
		arg.UpdatedAt,
	)
	return err
}

const upsertTrackCropByCatalogID = `-- name: UpsertTrackCropByCatalogID :exec
INSERT INTO track_crop (track_id, start_ms, end_ms, updated_at, catalog_id)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  start_ms = excluded.start_ms,
  end_ms = excluded.end_ms,
  updated_at = excluded.updated_at,
  catalog_id = excluded.catalog_id
`

type UpsertTrackCropByCatalogIDParams struct {
	TrackID   string         `json:"track_id"`
	StartMs   int64          `json:"start_ms"`
	EndMs     sql.NullInt64  `json:"end_ms"`
	UpdatedAt int64          `json:"updated_at"`
	CatalogID sql.NullString `json:"catalog_id"`
}

func (q *Queries) UpsertTrackCropByCatalogID(ctx context.Context, arg UpsertTrackCropByCatalogIDParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackCropByCatalogID,
		arg.TrackID,
		arg.StartMs,
		arg.EndMs,
		arg.UpdatedAt,
		arg.CatalogID,
	)
	return err
}
