// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: track_quality_overrides.sql

package db

import (
	"context"
)

const deleteTrackQualityOverride = `-- name: DeleteTrackQualityOverride :exec
DELETE FROM track_quality_override WHERE track_id = ?
`

func (q *Queries) DeleteTrackQualityOverride(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackQualityOverride, trackID)
	return err
}

const getTrackQualityOverride = `-- name: GetTrackQualityOverride :one
SELECT track_id, quality, updated_at FROM track_quality_override WHERE track_id = ?
`

func (q *Queries) GetTrackQualityOverride(ctx context.Context, trackID string) (TrackQualityOverride, error) {
	row := q.db.QueryRowContext(ctx, getTrackQualityOverride, trackID)
	var i TrackQualityOverride
	err := row.Scan(&i.TrackID, &i.Quality, &i.UpdatedAt)
	return i, err
}

const listTrackQualityOverrides = `-- name: ListTrackQualityOverrides :many
SELECT track_id, quality, updated_at FROM track_quality_override
`

func (q *Queries) ListTrackQualityOverrides(ctx context.Context) ([]TrackQualityOverride, error) {
	rows, err := q.db.QueryContext(ctx, listTrackQualityOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackQualityOverride
	for rows.Next() {
		var i TrackQualityOverride
		if err := rows.Scan(&i.TrackID, &i.Quality, &i.UpdatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertTrackQualityOverride = `-- name: UpsertTrackQualityOverride :exec
INSERT INTO track_quality_override (track_id, quality, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  quality = excluded.quality,
  updated_at = excluded.updated_at
`

type UpsertTrackQualityOverrideParams struct {
	TrackID   string `json:"track_id"`
	Quality   string `json:"quality"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertTrackQualityOverride(ctx context.Context, arg UpsertTrackQualityOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackQualityOverride, arg.TrackID, arg.Quality, arg.UpdatedAt)
	return err
}
