// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: track_quality_overrides.sql

package db

import (
	"context"
	"database/sql"
)

const deleteTrackQualityOverride = `-- name: DeleteTrackQualityOverride :exec
DELETE FROM track_quality_override WHERE track_id = ?
`

func (q *Queries) DeleteTrackQualityOverride(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackQualityOverride, trackID)
	return err
}

const deleteTrackQualityOverrideByCatalogID = `-- name: DeleteTrackQualityOverrideByCatalogID :exec
DELETE FROM track_quality_override WHERE catalog_id = ?
`

func (q *Queries) DeleteTrackQualityOverrideByCatalogID(ctx context.Context, catalogID sql.NullString) error {
	_, err := q.db.ExecContext(ctx, deleteTrackQualityOverrideByCatalogID, catalogID)
	return err
}

const getTrackQualityOverride = `-- name: GetTrackQualityOverride :one
SELECT track_id, quality, updated_at, catalog_id FROM track_quality_override WHERE track_id = ?
`

func (q *Queries) GetTrackQualityOverride(ctx context.Context, trackID string) (TrackQualityOverride, error) {
	row := q.db.QueryRowContext(ctx, getTrackQualityOverride, trackID)
	var i TrackQualityOverride
	err := row.Scan(
		&i.TrackID,
		&i.Quality,
		&i.UpdatedAt,
		&i.CatalogID,
	)
	return i, err
}

const getTrackQualityOverrideByCatalogID = `-- name: GetTrackQualityOverrideByCatalogID :one
SELECT track_id, quality, updated_at, catalog_id FROM track_quality_override WHERE catalog_id = ?
`

func (q *Queries) GetTrackQualityOverrideByCatalogID(ctx context.Context, catalogID sql.NullString) (TrackQualityOverride, error) {
	row := q.db.QueryRowContext(ctx, getTrackQualityOverrideByCatalogID, catalogID)
	var i TrackQualityOverride
	err := row.Scan(
		&i.TrackID,
		&i.Quality,
		&i.UpdatedAt,
		&i.CatalogID,
	)
	return i, err
}

const listTrackQualityOverrides = `-- name: ListTrackQualityOverrides :many
SELECT track_id, quality, updated_at, catalog_id FROM track_quality_override
`

func (q *Queries) ListTrackQualityOverrides(ctx context.Context) ([]TrackQualityOverride, error) {
	rows, err := q.db.QueryContext(ctx, listTrackQualityOverrides)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrackQualityOverride
	for rows.Next() {
		var i TrackQualityOverride
		if err := rows.Scan(
			&i.TrackID,
			&i.Quality,
			&i.UpdatedAt,
			&i.CatalogID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const repointTrackQualityOverrideCatalog = `-- name: RepointTrackQualityOverrideCatalog :exec
UPDATE track_quality_override SET catalog_id = ? WHERE catalog_id = ?
`

type RepointTrackQualityOverrideCatalogParams struct {
	CatalogID   sql.NullString `json:"catalog_id"`
	CatalogID_2 sql.NullString `json:"catalog_id_2"`
}

func (q *Queries) RepointTrackQualityOverrideCatalog(ctx context.Context, arg RepointTrackQualityOverrideCatalogParams) error {
	_, err := q.db.ExecContext(ctx, repointTrackQualityOverrideCatalog, arg.CatalogID, arg.CatalogID_2)
	return err
}

const upsertTrackQualityOverride = `-- name: UpsertTrackQualityOverride :exec
INSERT INTO track_quality_override (track_id, quality, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  quality = excluded.quality,
  updated_at = excluded.updated_at
`

type UpsertTrackQualityOverrideParams struct {
	TrackID   string `json:"track_id"`
	Quality   string `json:"quality"`
	UpdatedAt int64  `json:"updated_at"`
}

func (q *Queries) UpsertTrackQualityOverride(ctx context.Context, arg UpsertTrackQualityOverrideParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackQualityOverride, arg.TrackID, arg.Quality, arg.UpdatedAt)
	return err
}

const upsertTrackQualityOverrideByCatalogID = `-- name: UpsertTrackQualityOverrideByCatalogID :exec
INSERT INTO track_quality_override (track_id, quality, updated_at, catalog_id)
VALUES (?, ?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  quality = excluded.quality,
  updated_at = excluded.updated_at,
  catalog_id = excluded.catalog_id
`

type UpsertTrackQualityOverrideByCatalogIDParams struct {
	TrackID   string         `json:"track_id"`
	Quality   string         `json:"quality"`
	UpdatedAt int64          `json:"updated_at"`
	CatalogID sql.NullString `json:"catalog_id"`
}

func (q *Queries) UpsertTrackQualityOverrideByCatalogID(ctx context.Context, arg UpsertTrackQualityOverrideByCatalogIDParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackQualityOverrideByCatalogID,
		arg.TrackID,
		arg.Quality,
		arg.UpdatedAt,
		arg.CatalogID,
	)
	return err
}
