// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: track_duration.sql

package db

import (
	"context"
)

const deleteTrackDuration = `-- name: DeleteTrackDuration :exec
DELETE FROM track_duration WHERE track_id = ?
`

func (q *Queries) DeleteTrackDuration(ctx context.Context, trackID string) error {
	_, err := q.db.ExecContext(ctx, deleteTrackDuration, trackID)
	return err
}

const getTrackDuration = `-- name: GetTrackDuration :one
SELECT track_id, duration_ms, updated_at FROM track_duration WHERE track_id = ?
`

func (q *Queries) GetTrackDuration(ctx context.Context, trackID string) (TrackDuration, error) {
	row := q.db.QueryRowContext(ctx, getTrackDuration, trackID)
	var i TrackDuration
	err := row.Scan(&i.TrackID, &i.DurationMs, &i.UpdatedAt)
	return i, err
}

const upsertTrackDuration = `-- name: UpsertTrackDuration :exec
INSERT INTO track_duration (track_id, duration_ms, updated_at)
VALUES (?, ?, ?)
ON CONFLICT(track_id) DO UPDATE SET
  duration_ms = excluded.duration_ms,
  updated_at = excluded.updated_at
`

type UpsertTrackDurationParams struct {
	TrackID    string `json:"track_id"`
	DurationMs int64  `json:"duration_ms"`
	UpdatedAt  int64  `json:"updated_at"`
}

func (q *Queries) UpsertTrackDuration(ctx context.Context, arg UpsertTrackDurationParams) error {
	_, err := q.db.ExecContext(ctx, upsertTrackDuration, arg.TrackID, arg.DurationMs, arg.UpdatedAt)
	return err
}
